apiVersion: v1
kind: Service
metadata:
  name: server-kotlin
spec:
  ports:
    - nodePort: 32341
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: server-kotlin
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-kotlin
spec:
  selector:
    matchLabels:
      app: server-kotlin
  replicas: 1
  template:
    metadata:
      labels:
        app: server-kotlin
    spec:
      containers:
        - name: server-kotlin
          image: cityvizor/server-kotlin:93-redesign-cityvizor.cz
          env:
            - name: JDBC_URL
              valueFrom:
                configMapKeyRef:
                  name: server-kotlin-config
                  key: jdbc.url
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: server-kotlin-config
                  key: db.user
            - name: DB_PASS
              valueFrom:
                configMapKeyRef:
                  name: server-kotlin-config
                  key: db.pass
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /api/v2/health
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 3

