version: "3.8"

services:
    # We don't need the nginx container when developing. This effectively removes it.
    # https://stackoverflow.com/a/45385268/5127149
    nginx.cityvizor.otevrenamesta:
        image: tianon/true
        command: ""
        entrypoint: ""

    client.cityvizor.otevrenamesta:
        build:
            target: dev
        volumes:
            - ./client:/user/src/app
            - /user/src/app/node_modules
        ports:
            - 4200:4200
            - 49153:49153

    server.cityvizor.otevrenamesta:
        build:
            target: dev
        command: -w db.cityvizor.otevrenamesta -a -m server-dev -i
        ports:
            - 3000:3000
        volumes:
            - ./server:/home/node/app/
            - /home/node/app/node_modules

    worker.cityvizor.otevrenamesta:
        build:
            target: dev
        command: -w db.cityvizor.otevrenamesta -a -m worker-dev -i
        volumes:
            - ./server:/home/node/app/
            - /home/node/app/node_modules

    landing.cityvizor.otevrenamesta:
        build:
            target: dev
        ports:
            - 4202:8080
        volumes:
            - ./landing-page/src:/home/node/app/src
            - ./landing-page/cfg:/home/node/app/cfg
        
