version: "3.8"

services:
    proxy:
      volumes:
        - ./nginx/dev-with-nginx/:/etc/nginx:ro
    cityvizor-client:
        build:
            target: dev
        volumes:
            - ./client:/user/src/app
            - /user/src/app/node_modules
        ports:
            - 49153:49153
        environment:
            NODE_ENV: localnginx

    cityvizor-server:
        build:
            target: dev
        command: -w db.cityvizor.otevrenamesta -a -m server-dev -i
        volumes:
            - ./server:/home/node/app/
            - /home/node/app/node_modules
    cityvizor-worker:
        build:
            target: dev
        command: -w db.cityvizor.otevrenamesta -a -m worker-dev -i
        volumes:
            - ./server:/home/node/app/
            - /home/node/app/node_modules
    landing-page:
        build:
            target: dev
        volumes:
            - ./landing-page/src:/user/src/app/src
            - ./landing-page/cfg:/user/src/app/cfg