version: "3.8"

services:
    # We don't need the nginx container when developing. This effectively removes it.
    # https://stackoverflow.com/a/45385268/5127149
    proxy:
        image: tianon/true
        command: ""
        entrypoint: ""
    cityvizor-client:
        build:
            target: dev
        volumes:
            - ./client:/user/src/app
            - /user/src/app/node_modules
        ports:
            - 4200:4200
            - 49153:49153
    cityvizor-server:
        build:
            target: dev
        command: -w db.cityvizor.otevrenamesta -a -m server-dev
        ports:
            - 3000:3000
        volumes:
            - ./server:/user/src/app
            - /user/src/app/node_modules
    cityvizor-worker:
        build:
            target: dev
        command: -w db.cityvizor.otevrenamesta -a -m worker-dev
        volumes:
            - ./server:/user/src/app
            - /user/src/app/node_modules
