server {

    listen 0.0.0.0:80;
    listen [::]:80;

    root /usr/share/nginx/html;

    location = /index.html {
        add_header Cache-Control "no-cache, must-revalidate" always;
    }

    location ~* \.js$ {
        try_files $uri =404;
    }

    location / {
        location /assets/js/content.json { if_modified_since off; etag off; }

        try_files $uri /index.html =404;
    }

}
