server_strapi:
  database_host: cityvizor.chpsyfbvypjs.eu-central-1.rds.amazonaws.com
  database_username: strapi_test
  database_password: str@pi_t3st
  database_name: strapi_test


server_kotlin:
  jdbc_url: jdbc:postgresql://cityvizor.chpsyfbvypjs.eu-central-1.rds.amazonaws.com/cityvizor_test
  db_pass: 'cityv!zor_t3st'
  google_secrets_path: /home/ubuntu/cityvizor/server-kotlin/src/test/resources/city_request/test-credentials.json

ingress:
  main_host: cityvizor.ceskodigital.net
  strapi_host: cityvizor-api.ceskodigital.net
