apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: cityvizor-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - {{ .Values.ingress.main_host }}
        - {{ .Values.ingress.strapi_host }}
      secretName: cityvizor-tls
  rules:
    - host: {{ .Values.ingress.main_host }}
      http:
        paths:
          - path: /api/v2/
            backend:
              serviceName: server-kotlin
              servicePort: 8080
          - path: /api/v1/citysync
            backend:
              serviceName: server-kotlin
              servicePort: 8080
          - path: /
            backend:
              serviceName: client-redesign
              servicePort: 80
          - path: /strapi
            backend:
              serviceName: server-strapi
              servicePort: 1337
    - host: {{ .Values.ingress.strapi_host }}
      http:
        paths:
          - path: /
            backend:
              serviceName: server-strapi
              servicePort: 1337
