apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: 2016-02-18T19:14:38Z
  name: server-kotlin-config
  namespace: default
data:
  jdbc.url: {{ .Values.server_kotlin.jdbc_url }}
  db.user: {{ .Values.server_kotlin.db_user }}
  db.pass: {{ .Values.server_kotlin.db_pass }}

