apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: 2016-02-18T19:14:38Z
  name: server-strapi-config
  namespace: default
data:
  database.host: {{ .Values.server_strapi.database_host }}
  database.name: {{ .Values.server_strapi.database_name }}
  database.username: {{ .Values.server_strapi.database_username }}
  database.password: {{ .Values.server_strapi.database_password }}

