version: "3"
services:
  app:
    build: .
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=quickstart

  postgres:
    image: postgres:11.4-alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=mysecretpassword
