const rows = [
  {codelist: 'pbo-su-exp-groups', id: 50, name: 'Spotřebované nákupy'},
  {codelist: 'pbo-su-exp-groups', id: 51, name: 'Služby'},
  {codelist: 'pbo-su-exp-groups', id: 52, name: 'Osobní náklady'},
  {codelist: 'pbo-su-exp-groups', id: 53, name: 'Daně a poplatky'},
  {codelist: 'pbo-su-exp-groups', id: 54, name: 'Jiné provozní náklady'},
  {
    codelist: 'pbo-su-exp-groups',
    id: 55,
    name: 'Odpisy, rezervy, komplexní náklady příštích období a opravné položky v provozní oblasti',
  },
  {codelist: 'pbo-su-exp-groups', id: 56, name: 'Finanční náklady'},
  {
    codelist: 'pbo-su-exp-groups',
    id: 57,
    name: 'Rezervy a opravné položky ve finanční oblasti',
  },
  {
    codelist: 'pbo-su-exp-groups',
    id: 58,
    name: 'Změna stavu zásob vlastní činnosti a aktivace',
  },
  {
    codelist: 'pbo-su-exp-groups',
    id: 59,
    name: 'Daně z příjmů, převodové účty a rezerva na daň z příjmů',
  },
  {
    codelist: 'pbo-su-inc-groups',
    id: 60,
    name: 'Tržby za vlastní výkony a zboží',
  },
  {codelist: 'pbo-su-inc-groups', id: 61, name: '61x'},
  {codelist: 'pbo-su-inc-groups', id: 62, name: '62x'},
  {codelist: 'pbo-su-inc-groups', id: 63, name: 'Výnosy z daní a poplatků'},
  {codelist: 'pbo-su-inc-groups', id: 64, name: 'Jiné provozní výnosy'},
  {codelist: 'pbo-su-inc-groups', id: 65, name: '65x'},
  {codelist: 'pbo-su-inc-groups', id: 66, name: 'Finanční výnosy'},
  {codelist: 'pbo-su-inc-groups', id: 67, name: 'Výnosy z transferů'},
  {
    codelist: 'pbo-su-inc-groups',
    id: 68,
    name: 'Výnosy ze sdílených daní a poplatků',
  },
  {codelist: 'pbo-su-inc-groups', id: 69, name: 'Převodové účty'},
  {codelist: 'pbo-su', id: '501', name: 'Spotřeba materiálu'},
  {codelist: 'pbo-su', id: '502', name: 'Spotřeba energie'},
  {
    codelist: 'pbo-su',
    id: '503',
    name: 'Spotřeba jiných neskladovatelných dodávek',
  },
  {codelist: 'pbo-su', id: '504', name: 'Prodané zboží'},
  {codelist: 'pbo-su', id: '506', name: 'Aktivace dlouhodobého majetku'},
  {codelist: 'pbo-su', id: '507', name: 'Aktivace oběžného majetku'},
  {codelist: 'pbo-su', id: '508', name: 'Změna stavu zásob vlastní výroby'},
  {codelist: 'pbo-su', id: '511', name: 'Opravy a udržování'},
  {codelist: 'pbo-su', id: '512', name: 'Cestovné'},
  {codelist: 'pbo-su', id: '513', name: 'Náklady na reprezentaci'},
  {codelist: 'pbo-su', id: '516', name: 'Aktivace vnitroorganizačních služeb'},
  {codelist: 'pbo-su', id: '518', name: 'Ostatní služby'},
  {codelist: 'pbo-su', id: '521', name: 'Mzdové náklady'},
  {codelist: 'pbo-su', id: '524', name: 'Zákonné sociální pojištění'},
  {codelist: 'pbo-su', id: '525', name: 'Jiné sociální pojištění'},
  {codelist: 'pbo-su', id: '527', name: 'Zákonné sociální náklady'},
  {codelist: 'pbo-su', id: '528', name: 'Jiné sociální náklady'},
  {codelist: 'pbo-su', id: '531', name: 'Daň silniční'},
  {codelist: 'pbo-su', id: '532', name: 'Daň z nemovitostí'},
  {codelist: 'pbo-su', id: '538', name: 'Jiné daně a poplatky'},
  {codelist: 'pbo-su', id: '539', name: 'Vratky nepřímých daní'},
  {codelist: 'pbo-su', id: '541', name: 'Smluvní pokuty a úroky z prodlení'},
  {codelist: 'pbo-su', id: '542', name: 'Jiné pokuty a penále'},
  {codelist: 'pbo-su', id: '543', name: 'Dary a jiná bezúplatná předání'},
  {codelist: 'pbo-su', id: '544', name: 'Prodaný materiál'},
  {codelist: 'pbo-su', id: '547', name: 'Manka a škody'},
  {codelist: 'pbo-su', id: '548', name: 'Tvorba fondů'},
  {codelist: 'pbo-su', id: '549', name: 'Ostatní náklady z činnosti'},
  {codelist: 'pbo-su', id: '551', name: 'Odpisy dlouhodobého majetku'},
  {codelist: 'pbo-su', id: '552', name: 'Prodaný dlouhodobý nehmotný majetek'},
  {codelist: 'pbo-su', id: '553', name: 'Prodaný dlouhodobý hmotný majetek'},
  {codelist: 'pbo-su', id: '554', name: 'Prodané pozemky'},
  {codelist: 'pbo-su', id: '555', name: 'Tvorba a zúčtování rezerv'},
  {codelist: 'pbo-su', id: '556', name: 'Tvorba a zúčtování opravných položek'},
  {codelist: 'pbo-su', id: '557', name: 'Náklady z vyřazených pohledávek'},
  {
    codelist: 'pbo-su',
    id: '558',
    name: 'Náklady z drobného dlouhodobého majetku',
  },
  {codelist: 'pbo-su', id: '561', name: 'Prodané cenné papíry a podíly'},
  {codelist: 'pbo-su', id: '562', name: 'Úroky'},
  {codelist: 'pbo-su', id: '563', name: 'Kurzové ztráty'},
  {codelist: 'pbo-su', id: '564', name: 'Náklady z přecenění reálnou hodnotou'},
  {codelist: 'pbo-su', id: '569', name: 'Ostatní finanční náklady'},
  {
    codelist: 'pbo-su',
    id: '571',
    name: 'Náklady vybraných ústředních vládních institucí na transfery',
  },
  {
    codelist: 'pbo-su',
    id: '572',
    name: 'Náklady vybraných místních vládních institucí na transfery',
  },
  {
    codelist: 'pbo-su',
    id: '575',
    name: 'Náklady vybraných ústředních vládních institucí na předfinancování transferů',
  },
  {
    codelist: 'pbo-su',
    id: '581',
    name: 'Náklady ze sdílené daně z příjmů fyzických osob',
  },
  {
    codelist: 'pbo-su',
    id: '582',
    name: 'Náklady ze sdílené daně z příjmů právnických osob',
  },
  {
    codelist: 'pbo-su',
    id: '584',
    name: 'Náklady ze sdílené daně z přidané hodnoty',
  },
  {
    codelist: 'pbo-su',
    id: '585',
    name: 'Náklady ze sdílených spotřebních daní',
  },
  {
    codelist: 'pbo-su',
    id: '586',
    name: 'Náklady z ostatních sdílených daní a poplatků',
  },
  {codelist: 'pbo-su', id: '591', name: 'Daň z příjmů'},
  {codelist: 'pbo-su', id: '595', name: 'Dodatečné odvody daně z příjmů'},
  {codelist: 'pbo-su', id: '601', name: 'Výnosy z prodeje vlastních výrobků'},
  {codelist: 'pbo-su', id: '602', name: 'Výnosy z prodeje služeb'},
  {codelist: 'pbo-su', id: '603', name: 'Výnosy z pronájmu'},
  {codelist: 'pbo-su', id: '604', name: 'Výnosy z prodaného zboží'},
  {codelist: 'pbo-su', id: '605', name: 'Výnosy ze správních poplatků'},
  {codelist: 'pbo-su', id: '606', name: 'Výnosy z místních poplatků'},
  {codelist: 'pbo-su', id: '607', name: 'Výnosy ze soudních poplatků'},
  {codelist: 'pbo-su', id: '609', name: 'Jiné výnosy z vlastních výkonů'},
  {
    codelist: 'pbo-su',
    id: '631',
    name: 'Výnosy z daně z příjmů fyzických osob',
  },
  {
    codelist: 'pbo-su',
    id: '632',
    name: 'Výnosy z daně z příjmů právnických osob',
  },
  {codelist: 'pbo-su', id: '633', name: 'Výnosy ze sociálního pojištění'},
  {codelist: 'pbo-su', id: '634', name: 'Výnosy z daně z přidané hodnoty'},
  {codelist: 'pbo-su', id: '635', name: 'Výnosy ze spotřebních daní'},
  {codelist: 'pbo-su', id: '636', name: 'Výnosy z majetkových daní'},
  {codelist: 'pbo-su', id: '637', name: 'Výnosy z energetických daní'},
  {codelist: 'pbo-su', id: '638', name: 'Výnosy z daně silniční'},
  {codelist: 'pbo-su', id: '639', name: 'Výnosy z ostatních daní a poplatků'},
  {codelist: 'pbo-su', id: '641', name: 'Smluvní pokuty a úroky z prodlení'},
  {codelist: 'pbo-su', id: '642', name: 'Jiné pokuty a penále'},
  {codelist: 'pbo-su', id: '643', name: 'Výnosy z vyřazených pohledávek'},
  {codelist: 'pbo-su', id: '644', name: 'Výnosy z prodeje materiálu'},
  {
    codelist: 'pbo-su',
    id: '645',
    name: 'Výnosy z prodeje dlouhodobého nehmotného majetku',
  },
  {
    codelist: 'pbo-su',
    id: '646',
    name: 'Výnosy z prodeje dlouhodobého hmotného majetku kromě pozemků',
  },
  {codelist: 'pbo-su', id: '647', name: 'Výnosy z prodeje pozemků'},
  {codelist: 'pbo-su', id: '648', name: 'Čerpání fondů'},
  {codelist: 'pbo-su', id: '649', name: 'Ostatní výnosy z činnosti'},
  {
    codelist: 'pbo-su',
    id: '661',
    name: 'Výnosy z prodeje cenných papírů a podílů',
  },
  {codelist: 'pbo-su', id: '662', name: 'Úroky'},
  {codelist: 'pbo-su', id: '663', name: 'Kurzové zisky'},
  {codelist: 'pbo-su', id: '664', name: 'Výnosy z přecenění reálnou hodnotou'},
  {
    codelist: 'pbo-su',
    id: '665',
    name: 'Výnosy z dlouhodobého finančního majetku',
  },
  {codelist: 'pbo-su', id: '669', name: 'Ostatní finanční výnosy'},
  {
    codelist: 'pbo-su',
    id: '671',
    name: 'Výnosy vybraných ústředních vládních institucí z transferů',
  },
  {
    codelist: 'pbo-su',
    id: '672',
    name: 'Výnosy vybraných místních vládních institucí z transferů',
  },
  {
    codelist: 'pbo-su',
    id: '675',
    name: 'Výnosy vybraných ústředních vládních institucí z předfinancování transferů',
  },
  {
    codelist: 'pbo-su',
    id: '681',
    name: 'Výnosy ze sdílené daně z příjmů fyzických osob',
  },
  {
    codelist: 'pbo-su',
    id: '682',
    name: 'Výnosy ze sdílené daně z příjmů právnických osob',
  },
  {
    codelist: 'pbo-su',
    id: '684',
    name: 'Výnosy ze sdílené daně z přidané hodnoty',
  },
  {codelist: 'pbo-su', id: '685', name: 'Výnosy ze sdílených spotřebních daní'},
  {codelist: 'pbo-su', id: '686', name: 'Výnosy ze sdílených majetkových daní'},
  {
    codelist: 'pbo-su',
    id: '688',
    name: 'Výnosy z ostatních sdílených daní a poplatků',
  },
];

exports.up = async function (knex) {
  await knex('data.codelists').insert(rows);
};

exports.down = async function (knex) {
  return knex('data.codelists')
    .where('codelist', 'pbo-su')
    .orWhere('codelist', 'pbo-su-exp-groups')
    .orWhere('codelist', 'pbo-su-inc-groups')
    .delete();
};
