const data = [
  {
    id: '1011',
    name: 'Udržování výrobního potenciálu zemědělství, zemědělský půdní fond a mimoprodukční funkce zemědělství',
  },
  {
    id: '1012',
    name: 'Podnikání a restrukturalizace v zemědělství a potravinářství',
  },
  {id: '1013', name: 'Genetický potenciál hospodářských zvířat, osiv a sádí'},
  {
    id: '1014',
    name: 'Ozdravování hospodářských zvířat, polních a speciálních plodin a zvláštní veterinární péče',
  },
  {id: '1019', name: 'Ostatní zemědělská a potravinářská činnost a rozvoj'},
  {id: '1021', name: 'Organizace trhu s produkty rostlinné výroby'},
  {
    id: '1022',
    name: 'Organizace trhu s výrobky vzniklými zpracováním produktů rostlinné výroby',
  },
  {id: '1023', name: 'Organizace trhu s produkty živočišné výroby'},
  {
    id: '1024',
    name: 'Organizace trhu s výrobky vzniklými zpracováním produktů živočišné výroby',
  },
  {
    id: '1029',
    name: 'Ostatní záležitosti regulace zemědělské produkce, organizace zemědělského trhu a poskytování podpor',
  },
  {id: '1031', name: 'Pěstební činnost'},
  {id: '1032', name: 'Podpora ostatních produkčních činností'},
  {id: '1036', name: 'Správa v lesním hospodářství'},
  {id: '1037', name: 'Celospolečenské funkce lesů'},
  {id: '1039', name: 'Ostatní záležitosti lesního hospodářství'},
  {id: '1061', name: 'Činnost ústředního orgánu státní správy v zemědělství'},
  {id: '1062', name: 'Činnost ostatních orgánů státní správy v zemědělství'},
  {id: '1063', name: 'Správa zemědělského majetku'},
  {id: '1069', name: 'Ostatní správa v zemědělství'},
  {id: '1070', name: 'Rybářství'},
  {id: '1081', name: 'Zemědělský výzkum a vývoj'},
  {id: '1082', name: 'Lesnický výzkum'},
  {id: '1091', name: 'Mezinárodní spolupráce v zemědělství'},
  {id: '1092', name: 'Mezinárodní spolupráce v lesním hospodářství'},
  {id: '1098', name: 'Ostatní výdaje na zemědělství'},
  {id: '1099', name: 'Ostatní výdaje na lesní hospodářství'},
  {id: '2111', name: 'Uhelné hornictví'},
  {id: '2112', name: 'Těžba nerostných surovin kromě paliv'},
  {id: '2113', name: 'Zpracování ropy a zemního plynu'},
  {id: '2114', name: 'Jaderné elektrárny'},
  {id: '2115', name: 'Úspora energie a obnovitelné zdroje'},
  {id: '2116', name: 'Jaderné palivo a ochrana před ionizujícím zářením'},
  {id: '2117', name: 'Elektrická energie'},
  {id: '2118', name: 'Energie jiná než elektrická'},
  {id: '2119', name: 'Ostatní záležitosti těžebního průmyslu a energetiky'},
  {id: '2121', name: 'Stavebnictví'},
  {id: '2122', name: 'Sběr a zpracování druhotných surovin'},
  {id: '2123', name: 'Podpora rozvoje průmyslových zón'},
  {
    id: '2124',
    name: 'Opatření ke zvýšení konkurenceschopnosti průmyslových odvětví',
  },
  {id: '2125', name: 'Podpora podnikání a inovací'},
  {id: '2129', name: 'Ostatní odvětvová a oborová opatření'},
  {id: '2131', name: 'Přímá podpora exportu'},
  {id: '2139', name: 'Ostatní záležitosti zahraničního obchodu'},
  {id: '2141', name: 'Vnitřní obchod'},
  {id: '2142', name: 'Ubytování a stravování'},
  {id: '2143', name: 'Cestovní ruch'},
  {id: '2144', name: 'Ostatní služby'},
  {
    id: '2161',
    name: 'Činnost ústředního orgánu státní správy v odvětví energetiky, průmyslu, stavebnictví, obchodu a služeb',
  },
  {
    id: '2162',
    name: 'Činnost ostatních orgánů státní správy v průmyslu, stavebnictví, obchodu a službách',
  },
  {
    id: '2169',
    name: 'Ostatní správa v průmyslu, stavebnictví, obchodu a službách',
  },
  {id: '2181', name: 'Výzkum a vývoj v palivech a energetice'},
  {id: '2182', name: 'Výzkum a vývoj v průmyslu kromě paliv a energetiky'},
  {id: '2183', name: 'Výzkum a vývoj ve službách'},
  {id: '2184', name: 'Výzkum a vývoj v obchodu a cestovním ruchu'},
  {id: '2185', name: 'Výzkum a vývoj ve stavebnictví'},
  {
    id: '2191',
    name: 'Mezinárodní spolupráce v průmyslu, stavebnictví, obchodu a službách',
  },
  {
    id: '2199',
    name: 'Záležitosti průmyslu, stavebnictví, obchodu a služeb jinde nezařazené',
  },
  {id: '2211', name: 'Dálnice'},
  {id: '2212', name: 'Silnice'},
  {id: '2219', name: 'Ostatní záležitosti pozemních komunikací'},
  {id: '2221', name: 'Provoz veřejné silniční dopravy'},
  {id: '2222', name: 'Kontrola technické způsobilosti vozidel'},
  {id: '2223', name: 'Bezpečnost silničního provozu'},
  {id: '2229', name: 'Ostatní záležitosti v silniční dopravě'},
  {id: '2231', name: 'Vodní cesty'},
  {id: '2232', name: 'Provoz vnitrozemské plavby'},
  {id: '2233', name: 'Záležitosti námořní dopravy'},
  {id: '2239', name: 'Ostatní záležitosti vnitrozemské plavby'},
  {id: '2241', name: 'Železniční dráhy'},
  {id: '2242', name: 'Provoz veřejné železniční dopravy'},
  {id: '2243', name: 'Drážní vozidla'},
  {id: '2249', name: 'Ostatní záležitosti železniční dopravy'},
  {id: '2251', name: 'Letiště'},
  {id: '2252', name: 'Zabezpečení letového provozu'},
  {id: '2253', name: 'Provoz civilní letecké dopravy'},
  {id: '2259', name: 'Ostatní záležitosti civilní letecké dopravy'},
  {id: '2261', name: 'Činnost ústředních orgánů státní správy v dopravě'},
  {id: '2262', name: 'Činnost ostatních orgánů státní správy v dopravě'},
  {id: '2269', name: 'Ostatní správa v dopravě'},
  {id: '2271', name: 'Ostatní dráhy'},
  {id: '2272', name: 'Provoz ostatních drah'},
  {id: '2279', name: 'Záležitosti ostatních drah jinde nezařazené'},
  {id: '2280', name: 'Výzkum a vývoj v dopravě'},
  {id: '2291', name: 'Mezinárodní spolupráce v dopravě'},
  {id: '2292', name: 'Dopravní obslužnost veřejnými službami - linková'},
  {id: '2293', name: 'Dopravní obslužnost mimo veřejnou službu'},
  {id: '2294', name: 'Dopravní obslužnost veřejnými službami - drážní'},
  {id: '2295', name: 'Dopravní obslužnost veřejnými službami - smíšená'},
  {id: '2299', name: 'Ostatní záležitosti v dopravě'},
  {id: '2310', name: 'Pitná voda'},
  {id: '2321', name: 'Odvádění a čištění odpadních vod a nakládání s kaly'},
  {id: '2322', name: 'Prevence znečišťování vody'},
  {id: '2329', name: 'Odvádění a čištění odpadních vod jinde nezařazené'},
  {id: '2331', name: 'Úpravy vodohospodářsky významných a vodárenských toků'},
  {
    id: '2332',
    name: 'Vodní díla na vodohospodářsky významných a vodárenských tocích',
  },
  {id: '2333', name: 'Úpravy drobných vodních toků'},
  {id: '2334', name: 'Revitalizace říčních systémů'},
  {
    id: '2339',
    name: 'Záležitosti vodních toků a vodohospodářských děl jinde nezařazené',
  },
  {id: '2341', name: 'Vodní díla v zemědělské krajině'},
  {id: '2342', name: 'Protierozní ochrana'},
  {id: '2349', name: 'Ostatní záležitosti vody v zemědělské krajině'},
  {
    id: '2361',
    name: 'Činnost ústředních orgánů státní správy ve vodním hospodářství',
  },
  {
    id: '2362',
    name: 'Činnost ostatních orgánů státní správy ve vodním hospodářství',
  },
  {id: '2369', name: 'Ostatní správa ve vodním hospodářství'},
  {id: '2380', name: 'Vodohospodářský výzkum a vývoj'},
  {id: '2391', name: 'Mezinárodní spolupráce v oblasti vodního hospodářství'},
  {id: '2399', name: 'Ostatní záležitosti vodního hospodářství'},
  {id: '2411', name: 'Záležitosti pošt'},
  {id: '2412', name: 'Záležitosti telekomunikací'},
  {id: '2413', name: 'Záležitosti radiokomunikací'},
  {id: '2419', name: 'Ostatní záležitosti spojů'},
  {id: '2461', name: 'Činnost ústředních orgánů státní správy ve spojích'},
  {id: '2462', name: 'Činnost ostatních orgánů státní správy ve spojích'},
  {id: '2469', name: 'Ostatní správa ve spojích'},
  {id: '2480', name: 'Výzkum a vývoj ve spojích'},
  {id: '2491', name: 'Mezinárodní spolupráce ve spojích'},
  {id: '2499', name: 'Ostatní záležitosti spojů'},
  {id: '2510', name: 'Podpora podnikání'},
  {id: '2521', name: 'Bezpečnost práce'},
  {id: '2529', name: 'Všeobecné pracovní záležitosti jinde nezařazené'},
  {id: '2531', name: 'Centrální banka a měna'},
  {id: '2532', name: 'Úřad Národní rozpočtové rady'},
  {id: '2539', name: 'Všeobecné finanční záležitosti jinde nezařazené'},
  {id: '2541', name: 'Geologie'},
  {id: '2542', name: 'Meteorologie'},
  {id: '2549', name: 'Všeobecné hospodářské služby jinde nezařazené'},
  {
    id: '2561',
    name: 'Činnost ústředních orgánů státní správy v oblasti hospodářství',
  },
  {
    id: '2562',
    name: 'Činnost ostatních orgánů a organizací v oblasti normalizace, standardizace a metrologie',
  },
  {
    id: '2563',
    name: 'Činnost ostatních orgánů státní správy v zeměměřictví a katastru',
  },
  {id: '2564', name: 'Správa národního majetku'},
  {
    id: '2565',
    name: 'Činnost ostatních orgánů státní správy v oblasti bezpečnosti práce',
  },
  {id: '2569', name: 'Všeobecná hospodářská správa jinde nezařazená'},
  {
    id: '2580',
    name: 'Výzkum a vývoj v oblasti všeobecných hospodářských záležitostí',
  },
  {
    id: '2590',
    name: 'Mezinárodní spolupráce ve všeobecných hospodářských záležitostech.',
  },
  {id: '3111', name: 'Mateřské školy'},
  {
    id: '3112',
    name: 'Mateřské školy pro děti se speciálními vzdělávacími potřebami',
  },
  {id: '3113', name: 'Základní školy'},
  {
    id: '3114',
    name: 'Základní školy pro žáky se speciálními vzdělávacími potřebami',
  },
  {id: '3115', name: 'Ostatní záležitosti předškolního vzdělávání'},
  {id: '3117', name: 'První stupeň základních škol'},
  {id: '3118', name: 'Druhý stupeň základních škol'},
  {id: '3119', name: 'Ostatní záležitosti základního vzdělávání'},
  {id: '3121', name: 'Gymnazia'},
  {id: '3122', name: 'Střední odborné školy'},
  {
    id: '3123',
    name: 'Střední školy poskytující střední vzdělání s výučním listem',
  },
  {
    id: '3124',
    name: 'Střední školy a konzervatoře pro žáky se speciálními vzdělávacími potřebami',
  },
  {id: '3125', name: 'Střediska praktického vyučování a školní hospodářství'},
  {id: '3126', name: 'Konzervatoře'},
  {id: '3127', name: 'Střední školy'},
  {id: '3128', name: 'Sportovní školy - gymnázia'},
  {id: '3129', name: 'Ostatní zařízení středního vzdělávání'},
  {id: '3131', name: 'Výchovné ústavy a dětské domovy se školou'},
  {id: '3132', name: 'Diagnostické ústavy'},
  {id: '3133', name: 'Dětské domovy'},
  {
    id: '3139',
    name: 'Ostatní školská zařízení pro výkon ústavní a ochranné výchovy',
  },
  {id: '3141', name: 'Školní stravování'},
  {id: '3143', name: 'Školní družiny a kluby'},
  {id: '3144', name: 'Školy v přírodě'},
  {id: '3145', name: 'Internáty'},
  {id: '3146', name: 'Zařízení výchovného poradenství'},
  {id: '3147', name: 'Domovy mládeže'},
  {id: '3148', name: 'Střediska výchovné péče'},
  {
    id: '3149',
    name: 'Ostatní zařízení související s výchovou a vzděláváním mládeže',
  },
  {id: '3150', name: 'Vyšší odborné školy'},
  {id: '3211', name: 'Vysoké školy'},
  {id: '3212', name: 'Výzkum, vývoj a inovace na vysokých školách'},
  {id: '3213', name: 'Bakalářské studium'},
  {id: '3214', name: 'Magisterské a doktorské studium'},
  {id: '3221', name: 'Vysokoškolské koleje a menzy'},
  {
    id: '3229',
    name: 'Ostatní zařízení související s vysokoškolským vzděláváním',
  },
  {id: '3231', name: 'Základní umělecké školy'},
  {id: '3232', name: 'Jazykové školy s právem státní jazykové zkoušky'},
  {id: '3233', name: 'Střediska volného času'},
  {id: '3239', name: 'Záležitosti zájmového vzdělávání jinde nezařazené'},
  {id: '3261', name: 'Činnost ústředního orgánu státní správy ve vzdělávání'},
  {id: '3262', name: 'Činnost ostatních orgánů státní správy ve vzdělávání'},
  {id: '3269', name: 'Ostatní správa ve vzdělávání jinde nezařazená'},
  {id: '3280', name: 'Výzkum školství a vzdělávání'},
  {id: '3291', name: 'Mezinárodní spolupráce ve vzdělávání'},
  {id: '3292', name: 'Vzdělávání národnostních menšin a multikulturní výchova'},
  {id: '3293', name: 'Vzdělávací akce k integraci Romů'},
  {id: '3294', name: 'Zařízení pro další vzdělávání pedagogických pracovníků'},
  {id: '3299', name: 'Ostatní záležitosti vzdělávání'},
  {id: '3311', name: 'Divadelní činnost'},
  {id: '3312', name: 'Hudební činnost'},
  {
    id: '3313',
    name: 'Filmová tvorba, distribuce, kina a shromažďování audiovizuálních archiválií',
  },
  {id: '3314', name: 'Činnosti knihovnické'},
  {id: '3315', name: 'Činnosti muzeí a galerií'},
  {id: '3316', name: 'Vydavatelská činnost'},
  {id: '3317', name: 'Výstavní činnosti v kultuře'},
  {id: '3319', name: 'Ostatní záležitosti kultury'},
  {id: '3321', name: 'Činnosti památkových ústavů, hradů a zámků'},
  {id: '3322', name: 'Zachování a obnova kulturních památek'},
  {id: '3324', name: 'Výkup předmětů kulturní hodnoty'},
  {id: '3325', name: 'Pražský hrad'},
  {
    id: '3326',
    name: 'Pořízení, zachování a obnova hodnot místního kulturního, národního a historického povědomí',
  },
  {
    id: '3329',
    name: 'Ostatní záležitosti ochrany památek a péče o kulturní dědictví',
  },
  {
    id: '3330',
    name: 'Činnosti registrovaných církví a náboženských společností',
  },
  {id: '3341', name: 'Rozhlas a televize'},
  {id: '3349', name: 'Ostatní záležitosti sdělovacích prostředků'},
  {
    id: '3361',
    name: 'Činnost ústředního orgánu státní správy v oblasti kultury a církví',
  },
  {
    id: '3362',
    name: 'Činnost ostatních orgánů státní správy v oblasti kultury, církví a sdělovacích prostředků',
  },
  {
    id: '3369',
    name: 'Ostatní správa v oblasti kultury, církví a sdělovacích prostředků',
  },
  {
    id: '3380',
    name: 'Výzkum a vývoj v oblasti kultury, církví a sdělovacích prostředků',
  },
  {
    id: '3391',
    name: 'Mezinárodní spolupráce v kultuře, církvích a sdělovacích prostředcích',
  },
  {id: '3392', name: 'Zájmová činnost v kultuře'},
  {
    id: '3399',
    name: 'Ostatní záležitosti kultury, církví a sdělovacích prostředků',
  },
  {id: '3411', name: 'Státní sportovní reprezentace'},
  {id: '3412', name: 'Sportovní zařízení ve vlastnictví obce'},
  {id: '3419', name: 'Ostatní sportovní činnost'},
  {id: '3421', name: 'Využití volného času dětí a mládeže'},
  {id: '3429', name: 'Ostatní zájmová činnost a rekreace'},
  {
    id: '3461',
    name: 'Činnost ústředního orgánu státní správy v oblasti sportu',
  },
  {id: '3480', name: 'Výzkum v oblasti sportu, zájmové činnosti a rekreace'},
  {id: '3511', name: 'Všeobecná ambulantní péče'},
  {id: '3512', name: 'Stomatologická péče'},
  {id: '3513', name: 'Lékařská služba první pomoci'},
  {id: '3514', name: 'Transfúzní služba a tkáňová zařízení'},
  {id: '3515', name: 'Specializovaná ambulantní zdravotní péče'},
  {id: '3516', name: 'Péče v mateřství'},
  {id: '3519', name: 'Ostatní ambulantní péče'},
  {id: '3521', name: 'Fakultní nemocnice'},
  {id: '3522', name: 'Ostatní nemocnice'},
  {id: '3523', name: 'Odborné léčebné ústavy'},
  {id: '3524', name: 'Léčebny dlouhodobě nemocných'},
  {id: '3525', name: 'Hospice'},
  {id: '3526', name: 'Lázeňské léčebny, ozdravovny, sanatoria'},
  {
    id: '3527',
    name: 'Vysoce specializovaná pracoviště a jednooborové zařízení lůžkové péče',
  },
  {id: '3529', name: 'Ostatní ústavní péče'},
  {id: '3531', name: 'Hygienická služba a ochrana veřejného zdraví'},
  {
    id: '3532',
    name: 'Lékárenská služba (léky, protézy a přístroje pro užití vně zdravotnických zařízení)',
  },
  {id: '3533', name: 'Zdravotnická záchranná služba'},
  {id: '3534', name: 'Doprava ve zdravotnictví'},
  {
    id: '3539',
    name: 'Ostatní zdravotnická zařízení a služby pro zdravotnictví',
  },
  {
    id: '3541',
    name: 'Prevence před drogami, alkoholem, nikotinem aj. závislostmi',
  },
  {id: '3542', name: 'Prevence HIV/AIDS'},
  {id: '3543', name: 'Pomoc zdravotně postiženým a chronicky nemocným'},
  {id: '3544', name: 'Národní program zdraví'},
  {id: '3545', name: 'Programy paliativní péče'},
  {id: '3549', name: 'Ostatní speciální zdravotnická péče'},
  {
    id: '3561',
    name: 'Činnost ústředního orgánu státní správy ve zdravotnictví',
  },
  {id: '3562', name: 'Činnost ostatních orgánů státní správy ve zdravotnictví'},
  {id: '3569', name: 'Ostatní správa ve zdravotnictví jinde nezařazená'},
  {id: '3581', name: 'Organizace výzkumu a střediska vědeckých informací'},
  {id: '3589', name: 'Ostatní výzkum a vývoj ve zdravotnictví'},
  {id: '3591', name: 'Mezinárodní spolupráce ve zdravotnictví'},
  {id: '3592', name: 'Další vzdělávání pracovníků ve zdravotnictví'},
  {id: '3599', name: 'Ostatní činnost ve zdravotnictví'},
  {id: '3611', name: 'Podpora individuální bytové výstavby'},
  {id: '3612', name: 'Bytové hospodářství'},
  {id: '3613', name: 'Nebytové hospodářství'},
  {id: '3614', name: 'Bytové služby pro vlastní zaměstnance'},
  {id: '3615', name: 'Podpora stavebního spoření a hypotečních úvěrů'},
  {id: '3619', name: 'Ostatní rozvoj bydlení a bytového hospodářství'},
  {id: '3631', name: 'Veřejné osvětlení'},
  {id: '3632', name: 'Pohřebnictví'},
  {id: '3633', name: 'Výstavba a údržba místních inženýrských sítí'},
  {id: '3634', name: 'Lokální zásobování teplem'},
  {id: '3635', name: 'Územní plánování'},
  {id: '3636', name: 'Územní rozvoj'},
  {id: '3639', name: 'Komunální služby a územní rozvoj jinde nezařazené'},
  {
    id: '3661',
    name: 'Činnost ústředního orgánu státní správy v oblasti bydlení, komunálních služeb a územního rozvoje',
  },
  {
    id: '3662',
    name: 'Činnost ostatních orgánů státní správy v oblasti bydlení, komunálních služeb a územního rozvoje',
  },
  {
    id: '3669',
    name: 'Ostatní správa v oblasti v oblasti bydlení, komunálních služeb a územního rozvoje jinde nezařazená',
  },
  {
    id: '3680',
    name: 'Výzkum a vývoj v oblasti bydlení, komunálních služeb a územního rozvoje',
  },
  {
    id: '3691',
    name: 'Mezinárodní spolupráce v oblasti bydlení, komunálních služeb a územního rozvoje',
  },
  {
    id: '3699',
    name: 'Ostatní záležitosti bydlení, komunálních služeb a územního rozvoje',
  },
  {id: '3711', name: 'Odstraňování tuhých emisí'},
  {id: '3712', name: 'Odstraňování plynných emisí'},
  {id: '3713', name: 'Změny technologií vytápění'},
  {
    id: '3714',
    name: 'Opatření ke snižování produkce skleníkových plynů a plynů poškozujících ozónovou vrstvu',
  },
  {
    id: '3715',
    name: 'Změny výrobních technologií za účelem výrazného odstranění emisí',
  },
  {id: '3716', name: 'Monitoring ochrany ovzduší'},
  {id: '3719', name: 'Ostatní činnosti k ochraně ovzduší'},
  {id: '3721', name: 'Sběr a svoz nebezpečných odpadů'},
  {id: '3722', name: 'Sběr a svoz komunálních odpadů'},
  {
    id: '3723',
    name: 'Sběr a svoz ostatních odpadů (jiných než nebezpečných a komunálních)',
  },
  {id: '3724', name: 'Využívání a zneškodňování nebezpečných odpadů'},
  {id: '3725', name: 'Využívání a zneškodňování komunálních odpadů'},
  {id: '3726', name: 'Využívání a zneškodňování ostatních odpadů'},
  {id: '3727', name: 'Prevence vzniku odpadů'},
  {id: '3728', name: 'Monitoring nakládání s odpady'},
  {id: '3729', name: 'Ostatní nakládání s odpady'},
  {
    id: '3731',
    name: 'Ochrana půdy a podzemní vody proti znečišťujícím infiltracím',
  },
  {id: '3732', name: 'Dekontaminace půd a čištění spodní vody'},
  {id: '3733', name: 'Monitoring půdy a podzemní vody'},
  {id: '3734', name: 'Předcházení a sanace zasolení půd'},
  {id: '3739', name: 'Ostatní ochrana půdy a spodní vody'},
  {id: '3741', name: 'Ochrana druhů a stanovišť'},
  {id: '3742', name: 'Chráněné části přírody'},
  {
    id: '3743',
    name: 'Rekultivace půdy v důsledku těžební a důlní činnosti, po skládkách odpadů apod.',
  },
  {id: '3744', name: 'Protierozní, protilavinová a protipožární ochrana'},
  {id: '3745', name: 'Péče o vzhled obcí a veřejnou zeleň'},
  {id: '3749', name: 'Ostatní činnosti k ochraně přírody a krajiny'},
  {
    id: '3751',
    name: 'Konstrukce a uplatnění protihlukových zařízení (protihlukové stěny a bariéry, okna, zapouzdření strojů apod.)',
  },
  {id: '3753', name: 'Monitoring ke zjišťování úrovně hluku a vibrací'},
  {id: '3759', name: 'Ostatní činnosti k omezení hluku a vibrací'},
  {
    id: '3761',
    name: 'Činnost ústředního orgánu státní správy v ochraně životního prostředí',
  },
  {
    id: '3762',
    name: 'Činnost ostatních orgánů státní správy v ochraně životního prostředí',
  },
  {id: '3769', name: 'Ostatní správa v ochraně životního prostředí'},
  {id: '3771', name: 'Protiradonová opatření'},
  {id: '3772', name: 'Přeprava a nakládání s radioaktivním odpadem'},
  {id: '3773', name: 'Monitoring k zajišťování úrovně radioaktivního záření'},
  {id: '3779', name: 'Ostatní činnosti k ochraně proti záření'},
  {id: '3780', name: 'Výzkum životního prostředí'},
  {id: '3791', name: 'Mezinárodní spolupráce v životním prostředí'},
  {id: '3792', name: 'Ekologická výchova a osvěta'},
  {id: '3793', name: 'Ekologie v dopravě'},
  {id: '3799', name: 'Ostatní ekologické záležitosti'},
  {id: '3801', name: 'Akademie věd České republiky'},
  {id: '3802', name: 'Grantová agentura České republiky'},
  {id: '3803', name: 'Technologická agentura České republiky'},
  {id: '3809', name: 'Ostatní výzkum a vývoj odvětvově nespecifikovaný'},
  {
    id: '3900',
    name: 'Ostatní činnosti související se službami pro obyvatelstvo',
  },
  {id: '4111', name: 'Starobní důchody'},
  {id: '4112', name: 'Invalidní důchody pro invaliditu třetího stupně'},
  {id: '4113', name: 'Invalidní důchody pro invaliditu druhého stupně'},
  {id: '4114', name: 'Vdovské důchody'},
  {id: '4115', name: 'Vdovecké důchody'},
  {id: '4116', name: 'Sirotčí důchody'},
  {id: '4117', name: 'Invalidní důchody pro invaliditu prvního stupně'},
  {id: '4119', name: 'Ostatní dávky důchodového pojištění'},
  {id: '4121', name: 'Nemocenské'},
  {id: '4122', name: 'Ošetřovné'},
  {id: '4123', name: 'Vyrovnávací příspěvek v těhotenství a mateřství'},
  {id: '4124', name: 'Peněžitá pomoc v mateřství'},
  {id: '4125', name: 'Dávky otcovské poporodní péče'},
  {id: '4126', name: 'Dlouhodobé ošetřovné'},
  {id: '4129', name: 'Dávky nemocenského pojištění jinde nezařazené'},
  {id: '4131', name: 'Přídavek na dítě'},
  {id: '4132', name: 'Sociální příplatek'},
  {id: '4133', name: 'Porodné'},
  {id: '4134', name: 'Rodičovský příspěvek'},
  {id: '4136', name: 'Dávky pěstounské péče'},
  {id: '4138', name: 'Pohřebné'},
  {id: '4141', name: 'Příspěvek na bydlení'},
  {id: '4142', name: 'Příspěvek na školní pomůcky'},
  {id: '4149', name: 'Dávky státní sociální podpory jinde nezařazené'},
  {id: '4151', name: 'Odchodné'},
  {id: '4152', name: 'Výsluhový příspěvek'},
  {id: '4153', name: 'Úmrtné a příspěvek na pohřeb příslušníka'},
  {id: '4154', name: 'Odbytné'},
  {
    id: '4159',
    name: 'Ostatní sociální dávky příslušníků ozbrojených sil při skončení služebního poměru',
  },
  {id: '4171', name: 'Příspěvek na živobytí'},
  {id: '4172', name: 'Doplatek na bydlení'},
  {id: '4173', name: 'Mimořádná okamžitá pomoc'},
  {id: '4174', name: 'Dávky sociální péče pro staré občany'},
  {id: '4175', name: 'Dávky sociální péče pro rodinu a děti'},
  {id: '4176', name: 'Dávky sociální péče pro sociálně vyloučené'},
  {
    id: '4177',
    name: 'Mimořádná okamžitá pomoc osobám ohroženým sociálním vyloučením',
  },
  {id: '4179', name: 'Ostatní dávky sociální pomoci'},
  {id: '4182', name: 'Příspěvek na zvláštní pomůcky'},
  {id: '4183', name: 'Příspěvek na úpravu a provoz bezbariérového bytu'},
  {
    id: '4184',
    name: 'Příspěvky na zakoupení, opravu a zvláštní úpravu motorového vozidla',
  },
  {id: '4185', name: 'Příspěvek na provoz motorového vozidla'},
  {id: '4186', name: 'Příspěvek na individuální dopravu'},
  {id: '4187', name: 'Příspěvek na mobilitu'},
  {id: '4188', name: 'Příspěvek na zvláštní pomůcku'},
  {id: '4189', name: 'Ostatní dávky zdravotně postiženým občanům'},
  {id: '4191', name: 'Státní příspěvky na důchodové připojištění'},
  {id: '4192', name: 'Úrokové příspěvky mladým manželstvím'},
  {id: '4193', name: 'Dávky válečným veteránům a perzekvovaným osobám'},
  {id: '4194', name: 'Zvýšení důchodů pro bezmocnost'},
  {id: '4195', name: 'Příspěvek na péči'},
  {
    id: '4199',
    name: 'Ostatní dávky povahy sociálního zabezpečení jinde nezařazené',
  },
  {id: '4210', name: 'Podpory v nezaměstnanosti'},
  {id: '4221', name: 'Rekvalifikace'},
  {id: '4222', name: 'Veřejně prospěšné práce'},
  {id: '4223', name: 'Společensky účelná pracovní místa'},
  {id: '4225', name: 'Podpora zaměstnanosti zdravotně postižených občanů'},
  {id: '4226', name: 'Ostatní podpora zaměstnanosti'},
  {id: '4227', name: 'Cílené programy k řešení zaměstnanosti'},
  {id: '4229', name: 'Aktivní politika zaměstnanosti jinde nezařazená'},
  {
    id: '4230',
    name: 'Ochrana zaměstnanců při platební neschopnosti zaměstnavatelů',
  },
  {
    id: '4240',
    name: 'Příspěvek na podporu zaměstnávání osob se zdravotním postižením na chráněném trhu práce',
  },
  {id: '4250', name: 'Příspěvky na sociální důsledky restrukturalizace'},
  {id: '4280', name: 'Výzkum a vývoj v politice zaměstnanosti'},
  {id: '4311', name: 'Základní sociální poradenství'},
  {id: '4312', name: 'Odborné sociální poradenství'},
  {
    id: '4313',
    name: 'Sociální ústavy pro zdravotně postiženou mládež včetně diagnostických ústavů',
  },
  {id: '4314', name: 'Pečovatelská služba'},
  {id: '4315', name: 'Sociální hospitalizace'},
  {id: '4316', name: 'Domovy důchodců'},
  {id: '4317', name: 'Domovy - penziony pro staré občany'},
  {
    id: '4318',
    name: 'Ostatní sociální péče a pomoc starým občanům (kromě ústavní)',
  },
  {id: '4319', name: 'Ostatní výdaje související se sociálním poradenstvím'},
  {id: '4324', name: 'Zařízení pro děti vyžadující okamžitou pomoc'},
  {id: '4329', name: 'Ostatní sociální péče a pomoc dětem a mládeži'},
  {id: '4334', name: 'Pečovatelská služba pro rodinu a děti'},
  {id: '4339', name: 'Ostatní sociální péče a pomoc rodině a manželství'},
  {
    id: '4341',
    name: 'Sociální pomoc osobám v hmotné nouzi a občanům sociálně nepřizpůsobivým',
  },
  {id: '4342', name: 'Sociální péče a pomoc přistěhovalcům a vybraným etnikům'},
  {
    id: '4343',
    name: 'Sociální pomoc osobám v souvislosti s živelní pohromou nebo požárem',
  },
  {id: '4344', name: 'Sociální rehabilitace'},
  {id: '4345', name: 'Centra sociálně rehabilitačních služeb'},
  {
    id: '4349',
    name: 'Ostatní sociální péče a pomoc ostatním skupinám obyvatelstva',
  },
  {id: '4350', name: 'Domovy pro seniory'},
  {
    id: '4351',
    name: 'Osobní asistence, pečovatelská služba a podpora samostatného bydlení',
  },
  {id: '4352', name: 'Tísňová péče'},
  {id: '4353', name: 'Průvodcovské a předčitatelské služby'},
  {id: '4354', name: 'Chráněné bydlení'},
  {id: '4355', name: 'Týdenní stacionáře'},
  {id: '4356', name: 'Denní stacionáře a centra denních služeb'},
  {
    id: '4357',
    name: 'Domovy pro osoby se zdravotním postižením a domovy se zvláštním režimem',
  },
  {
    id: '4358',
    name: 'Sociální služby poskytované ve zdravotnických zařízeních ústavní péče',
  },
  {id: '4359', name: 'Ostatní služby a činnosti v oblasti sociální péče'},
  {
    id: '4361',
    name: 'Činnost ústředního orgánu státní správy v sociálním zabezpečení, politice zaměstnanosti a rodinné politice',
  },
  {
    id: '4362',
    name: 'Činnost ostatních orgánů státní správy v sociálním zabezpečení',
  },
  {
    id: '4363',
    name: 'Ostatní orgány státní správy v oblasti politiky zaměstnanosti',
  },
  {
    id: '4369',
    name: 'Ostatní správa v sociálním zabezpečení a politice zaměstnanosti',
  },
  {
    id: '4371',
    name: 'Raná péče a sociálně aktivizační služby pro rodiny s dětmi',
  },
  {id: '4372', name: 'Krizová pomoc'},
  {id: '4373', name: 'Domy na půl cesty'},
  {id: '4374', name: 'Azylové domy, nízkoprahová denní centra a noclehárny'},
  {id: '4375', name: 'Nízkoprahová zařízení pro děti a mládež'},
  {
    id: '4376',
    name: 'Služby následné péče, terapeutické komunity a kontaktní centra',
  },
  {id: '4377', name: 'Sociálně terapeutické dílny'},
  {id: '4378', name: 'Terénní programy'},
  {id: '4379', name: 'Ostatní služby a činnosti v oblasti sociální prevence'},
  {id: '4380', name: 'Výzkum v sociálním zabezpečení a politice zaměstnanosti'},
  {
    id: '4391',
    name: 'Mezinárodní spolupráce v sociálním zabezpečení a podpoře zaměstnanosti',
  },
  {id: '4392', name: 'Inspekce poskytování sociálních služeb'},
  {
    id: '4399',
    name: 'Ostatní záležitosti sociálních věcí a politiky zaměstnanosti',
  },
  {id: '5111', name: 'Armáda'},
  {id: '5112', name: 'Ostatní ozbrojené síly'},
  {id: '5113', name: 'Bezpečnostní složky ozbrojených sil'},
  {id: '5119', name: 'Podpůrné složky ozbrojených sil'},
  {
    id: '5161',
    name: 'Činnost ústředního orgánu státní správy ve vojenské obraně',
  },
  {
    id: '5162',
    name: 'Činnost ostatních orgánů státní správy ve vojenské obraně',
  },
  {id: '5169', name: 'Ostatní správa ve vojenské obraně'},
  {id: '5171', name: 'Zabezpečení potřeb ozbrojených sil'},
  {id: '5172', name: 'Operační příprava státního území'},
  {id: '5179', name: 'Ostatní činnosti pro zabezpečení potřeb ozbrojených sil'},
  {id: '5180', name: 'Výzkum a vývoj v oblasti obrany'},
  {id: '5191', name: 'Mezinárodní spolupráce v obraně'},
  {id: '5192', name: 'Zahraniční vojenská pomoc'},
  {id: '5199', name: 'Ostatní záležitosti obrany'},
  {id: '5211', name: 'Civilní ochrana-vojenská část'},
  {id: '5212', name: 'Ochrana obyvatelstva'},
  {id: '5213', name: 'Krizová opatření'},
  {id: '5219', name: 'Ostatní záležitosti ochrany obyvatelstva'},
  {id: '5220', name: 'Hospodářská opatření pro krizové stavy'},
  {
    id: '5261',
    name: 'Státní správa v oblasti hospodářských opatření pro krizové stavy a v oblasti krizového řízení',
  },
  {
    id: '5262',
    name: 'Činnost ostatních orgánů státní správy v oblasti civilního nouzového hospodářství',
  },
  {
    id: '5269',
    name: 'Ostatní správa v oblasti hospodářských opatření pro krizové stavy',
  },
  {
    id: '5271',
    name: 'Činnost orgánů krizového řízení na ústřední úrovni a dalších správních úřadů v oblasti krizového řízení',
  },
  {
    id: '5272',
    name: 'Činnost orgánů krizového řízení na územní úrovni a dalších územních správních úřadů v oblasti krizového řízení',
  },
  {id: '5273', name: 'Ostatní správa v oblasti krizového řízení'},
  {id: '5274', name: 'Podpora krizového řízení a nouzového plánování'},
  {id: '5279', name: 'Záležitosti krizového řízení jinde nezařazené'},
  {id: '5281', name: 'Výzkum a vývoj v oblasti ochrany obyvatelstva'},
  {id: '5289', name: 'Výzkum a vývoj v oblasti krizového řízení'},
  {id: '5291', name: 'Mezinárodní spolupráce v oblasti krizového řízení'},
  {
    id: '5292',
    name: 'Poskytnutí vzájemné zahraniční pomoci podle mezinárodních smluv',
  },
  {
    id: '5299',
    name: 'Ostatní záležitosti civilní připravenosti na krizové stavy',
  },
  {id: '5311', name: 'Bezpečnost a veřejný pořádek'},
  {
    id: '5312',
    name: 'Opatření proti legalizaci výnosů z trestné činnosti a proti financování terorismu',
  },
  {
    id: '5316',
    name: 'Činnost ústředního orgánu státní správy v oblasti bezpečnosti a veřejného pořádku',
  },
  {id: '5317', name: 'Hraniční přechody'},
  {id: '5319', name: 'Ostatní záležitosti bezpečnosti a veřejného pořádku'},
  {id: '5380', name: 'Výzkum týkající se bezpečnosti a veřejného pořádku'},
  {
    id: '5391',
    name: 'Mezinárodní spolupráce v oblasti bezpečnosti a veřejného pořádku',
  },
  {id: '5399', name: 'Ostatní záležitosti bezpečnosti,veřejného pořádku'},
  {id: '5410', name: 'Ústavní soud'},
  {id: '5420', name: 'Soudy'},
  {id: '5430', name: 'Státní zastupitelství'},
  {
    id: '5441',
    name: 'Činnost Generálního ředitelství Vězeňské služby a věznic',
  },
  {id: '5442', name: 'Ostatní správa ve vězeňství'},
  {id: '5449', name: 'Ostatní záležitosti vězeňství'},
  {id: '5450', name: 'Činnost probační a mediační služby'},
  {
    id: '5461',
    name: 'Činnost ústředního orgánu státní správy v oblasti právní ochrany',
  },
  {
    id: '5462',
    name: 'Činnost ostatních orgánů státní správy v oblasti právní ochrany',
  },
  {id: '5469', name: 'Ostatní správa v oblasti právní ochrany'},
  {id: '5470', name: 'Kancelář Veřejného ochránce práv'},
  {id: '5471', name: 'Kancelář finančního arbitra'},
  {id: '5480', name: 'Výzkum v oblasti právní ochrany'},
  {id: '5491', name: 'Mezinárodní spolupráce v oblasti právní ochrany'},
  {id: '5499', name: 'Ostatní záležitosti právní ochrany'},
  {id: '5511', name: 'Požární ochrana - profesionální část'},
  {id: '5512', name: 'Požární ochrana - dobrovolná část'},
  {id: '5517', name: 'Vzdělávací a technická zařízení požární ochrany'},
  {id: '5519', name: 'Ostatní záležitosti požární ochrany'},
  {
    id: '5521',
    name: 'Operační a informační střediska integrovaného záchranného systému.',
  },
  {id: '5522', name: 'Ostatní činnosti v integrovaném záchranném systému'},
  {
    id: '5529',
    name: 'Ostatní složky a činnosti integrovaného záchranného systému',
  },
  {
    id: '5561',
    name: 'Činnost ústředního orgánu státní správy v požární ochraně',
  },
  {
    id: '5562',
    name: 'Činnost ústředních orgánů státní správy v integrovaném záchranném systému',
  },
  {
    id: '5563',
    name: 'Činnost ostatních orgánů státní správy v integrovaném záchranném systému',
  },
  {
    id: '5580',
    name: 'Výzkum a vývoj v požární ochraně a integrovaném záchranném systému',
  },
  {
    id: '5591',
    name: 'Mezinárodní spolupráce v oblasti požární ochrany a integrovaném záchranném systému',
  },
  {
    id: '5592',
    name: 'Poskytnutí vzájemné zahraniční pomoci podle mezinárodních smluv',
  },
  {
    id: '5599',
    name: 'Ostatní záležitosti požární ochrany a integrovaného záchranného systému',
  },
  {id: '6111', name: 'Parlament'},
  {id: '6112', name: 'Zastupitelstva obcí'},
  {id: '6113', name: 'Zastupitelstva krajů'},
  {id: '6114', name: 'Volby do Parlamentu ČR'},
  {id: '6115', name: 'Volby do zastupitelstev územních samosprávných celků'},
  {id: '6116', name: 'Celostátní referendum'},
  {id: '6117', name: 'Volby do Evropského parlamentu'},
  {id: '6118', name: 'Volba prezidenta republiky'},
  {id: '6119', name: 'Ostatní zastupitelské orgány a volby'},
  {id: '6120', name: 'Kancelář prezidenta republiky'},
  {id: '6130', name: 'Nejvyšší kontrolní úřad'},
  {
    id: '6141',
    name: 'Ústřední orgány vnitřní státní správy a jejich dislokovaná pracoviště (nezařazené v jiných funkcích)',
  },
  {id: '6142', name: 'Finanční správa'},
  {id: '6143', name: 'Celní správa'},
  {id: '6145', name: 'Úřad vlády'},
  {id: '6146', name: 'Český statistický úřad'},
  {id: '6148', name: 'Plánování a statistika'},
  {id: '6149', name: 'Ostatní všeobecná vnitřní správa jinde nezařazená'},
  {
    id: '6151',
    name: 'Činnost ústředního orgánu státní správy v zahraniční službě',
  },
  {id: '6152', name: 'Zastupitelství a stálé mise ČR v zahraničí'},
  {id: '6153', name: 'Ostatní účast v mezinárodních vládních organizacích'},
  {id: '6159', name: 'Zahraniční služba a záležitosti jinde nezařazené'},
  {id: '6171', name: 'Činnost místní správy'},
  {id: '6172', name: 'Činnost regionální správy'},
  {id: '6173', name: 'Místní referendum'},
  {id: '6174', name: 'Činnost regionálních rad'},
  {id: '6180', name: 'Výzkum ve státní správě a samosprávě'},
  {id: '6190', name: 'Politické strany a hnutí'},
  {id: '6211', name: 'Archivní činnost'},
  {id: '6219', name: 'Ostatní veřejné služby jinde nezařazené.'},
  {id: '6221', name: 'Humanitární zahraniční pomoc přímá'},
  {id: '6222', name: 'Rozvojová zahraniční pomoc'},
  {id: '6223', name: 'Mezinárodní spolupráce (jinde nezařazená)'},
  {
    id: '6224',
    name: 'Humanitární zahraniční pomoc poskytovaná prostřednictvím mezinárodních organizací',
  },
  {id: '6229', name: 'Ostatní zahraniční pomoc'},
  {id: '6310', name: 'Obecné příjmy a výdaje z finančních operací'},
  {id: '6320', name: 'Pojištění funkčně nespecifikované'},
  {id: '6330', name: 'Převody vlastním fondům v rozpočtech územní úrovně'},
  {id: '6391', name: 'Soudní a mimosoudní rehabilitace'},
  {id: '6399', name: 'Ostatní finanční operace'},
  {id: '6401', name: 'Transfery všeobecné povahy jiným úrovním vlády'},
  {id: '6402', name: 'Finanční vypořádání minulých let'},
  {id: '6409', name: 'Ostatní činnosti jinde nezařazené'},
];

exports.up = async function (knex) {
  for (const paragraph of data) {
    if (
      (
        await knex('data.codelists')
          .where('id', paragraph.id)
          .andWhere('codelist', 'paragraphs')
      ).length > 0
    ) {
      await knex('data.codelists')
        .where('id', paragraph.id)
        .andWhere('codelist', 'paragraphs')
        .update('name', paragraph.name);
    } else {
      await knex('data.codelists').insert({
        codelist: 'paragraphs',
        ...paragraph,
      });
    }
  }
};

exports.down = async function (knex) {
  return knex('data.codelists').where('codelist', 'paragraphs').delete();
};
