export const BudgetParagraphs = {
	"0":{"name":"Pro příjmy (technický záznam)","parents":["Příjmy","Příjmy","Příjmy"]},
	"1011":{"name":"Udržování výrobního potenciálu zemědělství, zemědělský půdní fond a mimoprodukční funkce zemědělství","parents":["Zemědělství, lesní hospodářství a rybářství","Zemědělství, lesní hospodářství a rybářství","Zemědělská a potravinářská činnost a rozvoj"]},
	"1012":{"name":"Podnikání a restrukturalizace v zemědělství a potravinářství","parents":["Zemědělství, lesní hospodářství a rybářství","Zemědělství, lesní hospodářství a rybářství","Zemědělská a potravinářská činnost a rozvoj"]},
	"1013":{"name":"Genetický potenciál hospodářských zvířat, osiv a sádí","parents":["Zemědělství, lesní hospodářství a rybářství","Zemědělství, lesní hospodářství a rybářství","Zemědělská a potravinářská činnost a rozvoj"]},
	"1014":{"name":"Ozdravování hospodářských zvířat, polních a speciálních plodin a zvláštní veterinární péče","parents":["Zemědělství, lesní hospodářství a rybářství","Zemědělství, lesní hospodářství a rybářství","Zemědělská a potravinářská činnost a rozvoj"]},
	"1019":{"name":"Ostatní zemědělská a potravinářská činnost a rozvoj","parents":["Zemědělství, lesní hospodářství a rybářství","Zemědělství, lesní hospodářství a rybářství","Zemědělská a potravinářská činnost a rozvoj"]},
	"1021":{"name":"Organizace trhu s produkty rostlinné výroby","parents":["Zemědělství, lesní hospodářství a rybářství","Zemědělství, lesní hospodářství a rybářství","Regulace zemědělské produkce, organizace trhu a poskytování podpor"]},
	"1022":{"name":"Organizace trhu s výrobky vzniklými zpracováním produktů rostlinné výroby","parents":["Zemědělství, lesní hospodářství a rybářství","Zemědělství, lesní hospodářství a rybářství","Regulace zemědělské produkce, organizace trhu a poskytování podpor"]},
	"1023":{"name":"Organizace trhu s produkty živočišné výroby","parents":["Zemědělství, lesní hospodářství a rybářství","Zemědělství, lesní hospodářství a rybářství","Regulace zemědělské produkce, organizace trhu a poskytování podpor"]},
	"1024":{"name":"Organizace trhu s výrobky vzniklými zpracováním produktů živočišné výroby","parents":["Zemědělství, lesní hospodářství a rybářství","Zemědělství, lesní hospodářství a rybářství","Regulace zemědělské produkce, organizace trhu a poskytování podpor"]},
	"1029":{"name":"Ostatní záležitosti regulace zemědělské produkce, organizace zemědělského trhu a poskytování podpor","parents":["Zemědělství, lesní hospodářství a rybářství","Zemědělství, lesní hospodářství a rybářství","Regulace zemědělské produkce, organizace trhu a poskytování podpor"]},
	"1031":{"name":"Pěstební činnost","parents":["Zemědělství, lesní hospodářství a rybářství","Zemědělství, lesní hospodářství a rybářství","Lesní hospodářství"]},
	"1032":{"name":"Podpora ostatních produkčních činností","parents":["Zemědělství, lesní hospodářství a rybářství","Zemědělství, lesní hospodářství a rybářství","Lesní hospodářství"]},
	"1036":{"name":"Správa v lesním hospodářství","parents":["Zemědělství, lesní hospodářství a rybářství","Zemědělství, lesní hospodářství a rybářství","Lesní hospodářství"]},
	"1037":{"name":"Celospolečenské funkce lesů","parents":["Zemědělství, lesní hospodářství a rybářství","Zemědělství, lesní hospodářství a rybářství","Lesní hospodářství"]},
	"1039":{"name":"Ostatní záležitosti lesního hospodářství","parents":["Zemědělství, lesní hospodářství a rybářství","Zemědělství, lesní hospodářství a rybářství","Lesní hospodářství"]},
	"1061":{"name":"Činnost ústředního orgánu státní správy v zemědělství","parents":["Zemědělství, lesní hospodářství a rybářství","Zemědělství, lesní hospodářství a rybářství","Správa v zemědělství"]},
	"1062":{"name":"Činnost ostatních orgánů státní správy v zemědělství","parents":["Zemědělství, lesní hospodářství a rybářství","Zemědělství, lesní hospodářství a rybářství","Správa v zemědělství"]},
	"1063":{"name":"Správa zemědělského majetku","parents":["Zemědělství, lesní hospodářství a rybářství","Zemědělství, lesní hospodářství a rybářství","Správa v zemědělství"]},
	"1069":{"name":"Ostatní správa v zemědělství","parents":["Zemědělství, lesní hospodářství a rybářství","Zemědělství, lesní hospodářství a rybářství","Správa v zemědělství"]},
	"1070":{"name":"Rybářství","parents":["Zemědělství, lesní hospodářství a rybářství","Zemědělství, lesní hospodářství a rybářství","Rybářství"]},
	"1081":{"name":"Zemědělský výzkum a vývoj","parents":["Zemědělství, lesní hospodářství a rybářství","Zemědělství, lesní hospodářství a rybářství","Zemědělský a lesnický výzkum a vývoj"]},
	"1082":{"name":"Lesnický výzkum","parents":["Zemědělství, lesní hospodářství a rybářství","Zemědělství, lesní hospodářství a rybářství","Zemědělský a lesnický výzkum a vývoj"]},
	"1091":{"name":"Mezinárodní spolupráce v zemědělství","parents":["Zemědělství, lesní hospodářství a rybářství","Zemědělství, lesní hospodářství a rybářství","Ostatní činnost a nespecifikované výdaje"]},
	"1092":{"name":"Mezinárodní spolupráce v lesním hospodářství","parents":["Zemědělství, lesní hospodářství a rybářství","Zemědělství, lesní hospodářství a rybářství","Ostatní činnost a nespecifikované výdaje"]},
	"1098":{"name":"Ostatní výdaje na zemědělství","parents":["Zemědělství, lesní hospodářství a rybářství","Zemědělství, lesní hospodářství a rybářství","Ostatní činnost a nespecifikované výdaje"]},
	"1099":{"name":"Ostatní výdaje na lesní hospodářství","parents":["Zemědělství, lesní hospodářství a rybářství","Zemědělství, lesní hospodářství a rybářství","Ostatní činnost a nespecifikované výdaje"]},
	"2111":{"name":"Uhelné hornictví","parents":["Průmyslová a ostatní odvětví hospodářství","Průmysl, stavebnictví, obchod a služby","Záležitosti těžebního průmyslu a energetiky"]},
	"2112":{"name":"Těžba nerostných surovin kromě paliv","parents":["Průmyslová a ostatní odvětví hospodářství","Průmysl, stavebnictví, obchod a služby","Záležitosti těžebního průmyslu a energetiky"]},
	"2113":{"name":"Zpracování ropy a zemního plynu","parents":["Průmyslová a ostatní odvětví hospodářství","Průmysl, stavebnictví, obchod a služby","Záležitosti těžebního průmyslu a energetiky"]},
	"2114":{"name":"Jaderné elektrárny","parents":["Průmyslová a ostatní odvětví hospodářství","Průmysl, stavebnictví, obchod a služby","Záležitosti těžebního průmyslu a energetiky"]},
	"2115":{"name":"Úspora energie a obnovitelné zdroje","parents":["Průmyslová a ostatní odvětví hospodářství","Průmysl, stavebnictví, obchod a služby","Záležitosti těžebního průmyslu a energetiky"]},
	"2116":{"name":"Jaderné palivo a ochrana před ionizujícím zářením","parents":["Průmyslová a ostatní odvětví hospodářství","Průmysl, stavebnictví, obchod a služby","Záležitosti těžebního průmyslu a energetiky"]},
	"2117":{"name":"Elektrická energie","parents":["Průmyslová a ostatní odvětví hospodářství","Průmysl, stavebnictví, obchod a služby","Záležitosti těžebního průmyslu a energetiky"]},
	"2118":{"name":"Energie jiná než elektrická","parents":["Průmyslová a ostatní odvětví hospodářství","Průmysl, stavebnictví, obchod a služby","Záležitosti těžebního průmyslu a energetiky"]},
	"2119":{"name":"Ostatní záležitosti těžebního průmyslu a energetiky","parents":["Průmyslová a ostatní odvětví hospodářství","Průmysl, stavebnictví, obchod a služby","Záležitosti těžebního průmyslu a energetiky"]},
	"2121":{"name":"Stavebnictví","parents":["Průmyslová a ostatní odvětví hospodářství","Průmysl, stavebnictví, obchod a služby","Ostatní odvětvové a oborové záležitosti v průmyslu a stavebnictví"]},
	"2122":{"name":"Sběr a zpracování druhotných surovin","parents":["Průmyslová a ostatní odvětví hospodářství","Průmysl, stavebnictví, obchod a služby","Ostatní odvětvové a oborové záležitosti v průmyslu a stavebnictví"]},
	"2123":{"name":"Podpora rozvoje průmyslových zón","parents":["Průmyslová a ostatní odvětví hospodářství","Průmysl, stavebnictví, obchod a služby","Ostatní odvětvové a oborové záležitosti v průmyslu a stavebnictví"]},
	"2124":{"name":"Opatření ke zvýšení konkurenceschopnosti průmyslových odvětví","parents":["Průmyslová a ostatní odvětví hospodářství","Průmysl, stavebnictví, obchod a služby","Ostatní odvětvové a oborové záležitosti v průmyslu a stavebnictví"]},
	"2125":{"name":"Podpora podnikání a inovací","parents":["Průmyslová a ostatní odvětví hospodářství","Průmysl, stavebnictví, obchod a služby","Ostatní odvětvové a oborové záležitosti v průmyslu a stavebnictví"]},
	"2129":{"name":"Ostatní odvětvová a oborová opatření","parents":["Průmyslová a ostatní odvětví hospodářství","Průmysl, stavebnictví, obchod a služby","Ostatní odvětvové a oborové záležitosti v průmyslu a stavebnictví"]},
	"2131":{"name":"Přímá podpora exportu","parents":["Průmyslová a ostatní odvětví hospodářství","Průmysl, stavebnictví, obchod a služby","Zahraniční obchod"]},
	"2139":{"name":"Ostatní záležitosti zahraničního obchodu","parents":["Průmyslová a ostatní odvětví hospodářství","Průmysl, stavebnictví, obchod a služby","Zahraniční obchod"]},
	"2141":{"name":"Vnitřní obchod","parents":["Průmyslová a ostatní odvětví hospodářství","Průmysl, stavebnictví, obchod a služby","Vnitřní obchod, služby a cestovní ruch"]},
	"2142":{"name":"Ubytování a stravování","parents":["Průmyslová a ostatní odvětví hospodářství","Průmysl, stavebnictví, obchod a služby","Vnitřní obchod, služby a cestovní ruch"]},
	"2143":{"name":"Cestovní ruch","parents":["Průmyslová a ostatní odvětví hospodářství","Průmysl, stavebnictví, obchod a služby","Vnitřní obchod, služby a cestovní ruch"]},
	"2144":{"name":"Ostatní služby","parents":["Průmyslová a ostatní odvětví hospodářství","Průmysl, stavebnictví, obchod a služby","Vnitřní obchod, služby a cestovní ruch"]},
	"2161":{"name":"Činnost ústředního orgánu státní správy v odvětví energetiky, průmyslu, stavebnictví, obchodu a služeb","parents":["Průmyslová a ostatní odvětví hospodářství","Průmysl, stavebnictví, obchod a služby","Správa v odvětví energetiky, průmyslu, stavebnictví, obchodu a služeb"]},
	"2162":{"name":"Činnost ostatních orgánů státní správy v průmyslu, stavebnictví, obchodu a službách","parents":["Průmyslová a ostatní odvětví hospodářství","Průmysl, stavebnictví, obchod a služby","Správa v odvětví energetiky, průmyslu, stavebnictví, obchodu a služeb"]},
	"2169":{"name":"Ostatní správa v průmyslu, stavebnictví, obchodu a službách","parents":["Průmyslová a ostatní odvětví hospodářství","Průmysl, stavebnictví, obchod a služby","Správa v odvětví energetiky, průmyslu, stavebnictví, obchodu a služeb"]},
	"2181":{"name":"Výzkum a vývoj v palivech a energetice","parents":["Průmyslová a ostatní odvětví hospodářství","Průmysl, stavebnictví, obchod a služby","Výzkum a vývoj v průmyslu, stavebnictví, obchodu a službách"]},
	"2182":{"name":"Výzkum a vývoj v průmyslu kromě paliv a energetiky","parents":["Průmyslová a ostatní odvětví hospodářství","Průmysl, stavebnictví, obchod a služby","Výzkum a vývoj v průmyslu, stavebnictví, obchodu a službách"]},
	"2183":{"name":"Výzkum a vývoj ve službách","parents":["Průmyslová a ostatní odvětví hospodářství","Průmysl, stavebnictví, obchod a služby","Výzkum a vývoj v průmyslu, stavebnictví, obchodu a službách"]},
	"2184":{"name":"Výzkum a vývoj v obchodu a cestovním ruchu","parents":["Průmyslová a ostatní odvětví hospodářství","Průmysl, stavebnictví, obchod a služby","Výzkum a vývoj v průmyslu, stavebnictví, obchodu a službách"]},
	"2185":{"name":"Výzkum a vývoj ve stavebnictví","parents":["Průmyslová a ostatní odvětví hospodářství","Průmysl, stavebnictví, obchod a služby","Výzkum a vývoj v průmyslu, stavebnictví, obchodu a službách"]},
	"2191":{"name":"Mezinárodní spolupráce v průmyslu, stavebnictví, obchodu a službách","parents":["Průmyslová a ostatní odvětví hospodářství","Průmysl, stavebnictví, obchod a služby","Ostatní činnost a nespecifikované výdaje"]},
	"2199":{"name":"Záležitosti průmyslu, stavebnictví, obchodu a služeb jinde nezařazené","parents":["Průmyslová a ostatní odvětví hospodářství","Průmysl, stavebnictví, obchod a služby","Ostatní činnost a nespecifikované výdaje"]},
	"2211":{"name":"Dálnice","parents":["Průmyslová a ostatní odvětví hospodářství","Doprava","Pozemní komunikace"]},
	"2212":{"name":"Silnice","parents":["Průmyslová a ostatní odvětví hospodářství","Doprava","Pozemní komunikace"]},
	"2219":{"name":"Ostatní záležitosti pozemních komunikací","parents":["Průmyslová a ostatní odvětví hospodářství","Doprava","Pozemní komunikace"]},
	"2221":{"name":"Provoz veřejné silniční dopravy","parents":["Průmyslová a ostatní odvětví hospodářství","Doprava","Silniční doprava"]},
	"2222":{"name":"Kontrola technické způsobilosti vozidel","parents":["Průmyslová a ostatní odvětví hospodářství","Doprava","Silniční doprava"]},
	"2223":{"name":"Bezpečnost silničního provozu","parents":["Průmyslová a ostatní odvětví hospodářství","Doprava","Silniční doprava"]},
	"2229":{"name":"Ostatní záležitosti v silniční dopravě","parents":["Průmyslová a ostatní odvětví hospodářství","Doprava","Silniční doprava"]},
	"2231":{"name":"Vodní cesty","parents":["Průmyslová a ostatní odvětví hospodářství","Doprava","Vnitrozemská a námořní plavba"]},
	"2232":{"name":"Provoz vnitrozemské plavby","parents":["Průmyslová a ostatní odvětví hospodářství","Doprava","Vnitrozemská a námořní plavba"]},
	"2233":{"name":"Záležitosti námořní dopravy","parents":["Průmyslová a ostatní odvětví hospodářství","Doprava","Vnitrozemská a námořní plavba"]},
	"2239":{"name":"Ostatní záležitosti vnitrozemské plavby","parents":["Průmyslová a ostatní odvětví hospodářství","Doprava","Vnitrozemská a námořní plavba"]},
	"2241":{"name":"Železniční dráhy","parents":["Průmyslová a ostatní odvětví hospodářství","Doprava","Železniční doprava"]},
	"2242":{"name":"Provoz veřejné železniční dopravy","parents":["Průmyslová a ostatní odvětví hospodářství","Doprava","Železniční doprava"]},
	"2243":{"name":"Drážní vozidla","parents":["Průmyslová a ostatní odvětví hospodářství","Doprava","Železniční doprava"]},
	"2249":{"name":"Ostatní záležitosti železniční dopravy","parents":["Průmyslová a ostatní odvětví hospodářství","Doprava","Železniční doprava"]},
	"2251":{"name":"Letiště","parents":["Průmyslová a ostatní odvětví hospodářství","Doprava","Civilní letecká doprava"]},
	"2252":{"name":"Zabezpečení letového provozu","parents":["Průmyslová a ostatní odvětví hospodářství","Doprava","Civilní letecká doprava"]},
	"2253":{"name":"Provoz civilní letecké dopravy","parents":["Průmyslová a ostatní odvětví hospodářství","Doprava","Civilní letecká doprava"]},
	"2259":{"name":"Ostatní záležitosti civilní letecké dopravy","parents":["Průmyslová a ostatní odvětví hospodářství","Doprava","Civilní letecká doprava"]},
	"2261":{"name":"Činnost ústředních orgánů státní správy v dopravě","parents":["Průmyslová a ostatní odvětví hospodářství","Doprava","Správa v dopravě"]},
	"2262":{"name":"Činnost ostatních orgánů státní správy v dopravě","parents":["Průmyslová a ostatní odvětví hospodářství","Doprava","Správa v dopravě"]},
	"2269":{"name":"Ostatní správa v dopravě","parents":["Průmyslová a ostatní odvětví hospodářství","Doprava","Správa v dopravě"]},
	"2271":{"name":"Ostatní dráhy","parents":["Průmyslová a ostatní odvětví hospodářství","Doprava","Doprava ostatních drah"]},
	"2272":{"name":"Provoz ostatních drah","parents":["Průmyslová a ostatní odvětví hospodářství","Doprava","Doprava ostatních drah"]},
	"2279":{"name":"Záležitosti ostatních drah jinde nezařazené","parents":["Průmyslová a ostatní odvětví hospodářství","Doprava","Doprava ostatních drah"]},
	"2280":{"name":"Výzkum a vývoj v dopravě","parents":["Průmyslová a ostatní odvětví hospodářství","Doprava","Výzkum v dopravě"]},
	"2291":{"name":"Mezinárodní spolupráce v dopravě","parents":["Průmyslová a ostatní odvětví hospodářství","Doprava","Ostatní činnost a nespecifikované výdaje v dopravě"]},
	"2299":{"name":"Ostatní záležitosti v dopravě","parents":["Průmyslová a ostatní odvětví hospodářství","Doprava","Ostatní činnost a nespecifikované výdaje v dopravě"]},
	"2310":{"name":"Pitná voda","parents":["Průmyslová a ostatní odvětví hospodářství","Vodní hospodářství","Pitná voda"]},
	"2321":{"name":"Odvádění a čištění odpadních vod a nakládání s kaly","parents":["Průmyslová a ostatní odvětví hospodářství","Vodní hospodářství","Odvádění a čištění odpadních vod"]},
	"2322":{"name":"Prevence znečišťování vody","parents":["Průmyslová a ostatní odvětví hospodářství","Vodní hospodářství","Odvádění a čištění odpadních vod"]},
	"2329":{"name":"Odvádění a čištění odpadních vod jinde nezařazené","parents":["Průmyslová a ostatní odvětví hospodářství","Vodní hospodářství","Odvádění a čištění odpadních vod"]},
	"2331":{"name":"Úpravy vodohospodářsky významných a vodárenských toků","parents":["Průmyslová a ostatní odvětví hospodářství","Vodní hospodářství","Vodní toky a vodohospodářská díla"]},
	"2332":{"name":"Vodní díla na vodohospodářsky významných a vodárenských tocích","parents":["Průmyslová a ostatní odvětví hospodářství","Vodní hospodářství","Vodní toky a vodohospodářská díla"]},
	"2333":{"name":"Úpravy drobných vodních toků","parents":["Průmyslová a ostatní odvětví hospodářství","Vodní hospodářství","Vodní toky a vodohospodářská díla"]},
	"2334":{"name":"Revitalizace říčních systémů","parents":["Průmyslová a ostatní odvětví hospodářství","Vodní hospodářství","Vodní toky a vodohospodářská díla"]},
	"2339":{"name":"Záležitosti vodních toků a vodohospodářských děl jinde nezařazené","parents":["Průmyslová a ostatní odvětví hospodářství","Vodní hospodářství","Vodní toky a vodohospodářská díla"]},
	"2341":{"name":"Vodní díla v zemědělské krajině","parents":["Průmyslová a ostatní odvětví hospodářství","Vodní hospodářství","Voda v zemědělské krajině"]},
	"2342":{"name":"Protierozní ochrana","parents":["Průmyslová a ostatní odvětví hospodářství","Vodní hospodářství","Voda v zemědělské krajině"]},
	"2349":{"name":"Ostatní záležitosti vody v zemědělské krajině","parents":["Průmyslová a ostatní odvětví hospodářství","Vodní hospodářství","Voda v zemědělské krajině"]},
	"2361":{"name":"Činnost ústředních orgánů státní správy ve vodním hospodářství","parents":["Průmyslová a ostatní odvětví hospodářství","Vodní hospodářství","Správa ve vodním hospodářství"]},
	"2362":{"name":"Činnost ostatních orgánů státní správy ve vodním hospodářství","parents":["Průmyslová a ostatní odvětví hospodářství","Vodní hospodářství","Správa ve vodním hospodářství"]},
	"2369":{"name":"Ostatní správa ve vodním hospodářství","parents":["Průmyslová a ostatní odvětví hospodářství","Vodní hospodářství","Správa ve vodním hospodářství"]},
	"2380":{"name":"Vodohospodářský výzkum a vývoj","parents":["Průmyslová a ostatní odvětví hospodářství","Vodní hospodářství","Vodohospodářský výzkum a vývoj"]},
	"2391":{"name":"Mezinárodní spolupráce v oblasti vodního hospodářství","parents":["Průmyslová a ostatní odvětví hospodářství","Vodní hospodářství","Ostatní činnost a nespecifikované výdaje"]},
	"2399":{"name":"Ostatní záležitosti vodního hospodářství","parents":["Průmyslová a ostatní odvětví hospodářství","Vodní hospodářství","Ostatní činnost a nespecifikované výdaje"]},
	"2411":{"name":"Záležitosti pošt","parents":["Průmyslová a ostatní odvětví hospodářství","Spoje","Činnosti spojů"]},
	"2412":{"name":"Záležitosti telekomunikací","parents":["Průmyslová a ostatní odvětví hospodářství","Spoje","Činnosti spojů"]},
	"2413":{"name":"Záležitosti radiokomunikací","parents":["Průmyslová a ostatní odvětví hospodářství","Spoje","Činnosti spojů"]},
	"2419":{"name":"Ostatní záležitosti spojů","parents":["Průmyslová a ostatní odvětví hospodářství","Spoje","Činnosti spojů"]},
	"2461":{"name":"Činnost ústředních orgánů státní správy ve spojích","parents":["Průmyslová a ostatní odvětví hospodářství","Spoje","Správa ve spojích"]},
	"2462":{"name":"Činnost ostatních orgánů státní správy ve spojích","parents":["Průmyslová a ostatní odvětví hospodářství","Spoje","Správa ve spojích"]},
	"2469":{"name":"Ostatní správa ve spojích","parents":["Průmyslová a ostatní odvětví hospodářství","Spoje","Správa ve spojích"]},
	"2480":{"name":"Výzkum a vývoj ve spojích","parents":["Průmyslová a ostatní odvětví hospodářství","Spoje","Výzkum a vývoj ve spojích"]},
	"2491":{"name":"Mezinárodní spolupráce ve spojích","parents":["Průmyslová a ostatní odvětví hospodářství","Spoje","Ostatní činnost a nespecifikované výdaje ve spojích"]},
	"2499":{"name":"Ostatní záležitosti spojů","parents":["Průmyslová a ostatní odvětví hospodářství","Spoje","Ostatní činnost a nespecifikované výdaje ve spojích"]},
	"2510":{"name":"Podpora podnikání","parents":["Průmyslová a ostatní odvětví hospodářství","Všeobecné hospodářské záležitosti a ostatní ekonomické funkce","Podpora podnikání"]},
	"2521":{"name":"Bezpečnost práce","parents":["Průmyslová a ostatní odvětví hospodářství","Všeobecné hospodářské záležitosti a ostatní ekonomické funkce","Všeobecné pracovní záležitosti"]},
	"2529":{"name":"Všeobecné pracovní záležitosti jinde nezařazené","parents":["Průmyslová a ostatní odvětví hospodářství","Všeobecné hospodářské záležitosti a ostatní ekonomické funkce","Všeobecné pracovní záležitosti"]},
	"2531":{"name":"Centrální banka a měna","parents":["Průmyslová a ostatní odvětví hospodářství","Všeobecné hospodářské záležitosti a ostatní ekonomické funkce","Všeobecné finanční záležitosti"]},
	"2539":{"name":"Všeobecné finanční záležitosti jinde nezařazené","parents":["Průmyslová a ostatní odvětví hospodářství","Všeobecné hospodářské záležitosti a ostatní ekonomické funkce","Všeobecné finanční záležitosti"]},
	"2541":{"name":"Geologie","parents":["Průmyslová a ostatní odvětví hospodářství","Všeobecné hospodářské záležitosti a ostatní ekonomické funkce","Všeobecné hospodářské služby"]},
	"2542":{"name":"Meteorologie","parents":["Průmyslová a ostatní odvětví hospodářství","Všeobecné hospodářské záležitosti a ostatní ekonomické funkce","Všeobecné hospodářské služby"]},
	"2549":{"name":"Všeobecné hospodářské služby jinde nezařazené","parents":["Průmyslová a ostatní odvětví hospodářství","Všeobecné hospodářské záležitosti a ostatní ekonomické funkce","Všeobecné hospodářské služby"]},
	"2561":{"name":"Činnost ústředních orgánů státní správy v oblasti hospodářství","parents":["Průmyslová a ostatní odvětví hospodářství","Všeobecné hospodářské záležitosti a ostatní ekonomické funkce","Všeobecná hospodářská správa"]},
	"2562":{"name":"Činnost ostatních orgánů a organizací v oblasti normalizace, standardizace a metrologie","parents":["Průmyslová a ostatní odvětví hospodářství","Všeobecné hospodářské záležitosti a ostatní ekonomické funkce","Všeobecná hospodářská správa"]},
	"2563":{"name":"Činnost ostatních orgánů státní správy v zeměměřictví a katastru","parents":["Průmyslová a ostatní odvětví hospodářství","Všeobecné hospodářské záležitosti a ostatní ekonomické funkce","Všeobecná hospodářská správa"]},
	"2564":{"name":"Správa národního majetku","parents":["Průmyslová a ostatní odvětví hospodářství","Všeobecné hospodářské záležitosti a ostatní ekonomické funkce","Všeobecná hospodářská správa"]},
	"2565":{"name":"Činnost ostatních orgánů státní správy v oblasti bezpečnosti práce","parents":["Průmyslová a ostatní odvětví hospodářství","Všeobecné hospodářské záležitosti a ostatní ekonomické funkce","Všeobecná hospodářská správa"]},
	"2569":{"name":"Všeobecná hospodářská správa jinde nezařazená","parents":["Průmyslová a ostatní odvětví hospodářství","Všeobecné hospodářské záležitosti a ostatní ekonomické funkce","Všeobecná hospodářská správa"]},
	"2580":{"name":"Výzkum a vývoj v oblasti všeobecných hospodářských záležitostí","parents":["Průmyslová a ostatní odvětví hospodářství","Všeobecné hospodářské záležitosti a ostatní ekonomické funkce","Výzkum a vývoj v oblasti všeobecných hospodářských záležitostí"]},
	"2590":{"name":"Mezinárodní spolupráce ve všeobecných hospodářských záležitostech.","parents":["Průmyslová a ostatní odvětví hospodářství","Všeobecné hospodářské záležitosti a ostatní ekonomické funkce","Ostatní činnosti a nespecifikované výdaje"]},
	"3111":{"name":"Mateřské školy","parents":["Služby pro obyvatelstvo","Vzdělávání a školské služby","Předškolní a základní vzdělávání"]},
	"3112":{"name":"Mateřské školy pro děti se speciálními vzdělávacími potřebami","parents":["Služby pro obyvatelstvo","Vzdělávání a školské služby","Předškolní a základní vzdělávání"]},
	"3113":{"name":"Základní školy","parents":["Služby pro obyvatelstvo","Vzdělávání a školské služby","Předškolní a základní vzdělávání"]},
	"3114":{"name":"Základní školy pro žáky se speciálními vzdělávacími potřebami","parents":["Služby pro obyvatelstvo","Vzdělávání a školské služby","Předškolní a základní vzdělávání"]},
	"3115":{"name":"Ostatní záležitosti předškolního vzdělávání","parents":["Služby pro obyvatelstvo","Vzdělávání a školské služby","Předškolní a základní vzdělávání"]},
	"3117":{"name":"První stupeň základních škol","parents":["Služby pro obyvatelstvo","Vzdělávání a školské služby","Předškolní a základní vzdělávání"]},
	"3118":{"name":"Druhý stupeň základních škol","parents":["Služby pro obyvatelstvo","Vzdělávání a školské služby","Předškolní a základní vzdělávání"]},
	"3119":{"name":"Ostatní záležitosti základního vzdělávání","parents":["Služby pro obyvatelstvo","Vzdělávání a školské služby","Předškolní a základní vzdělávání"]},
	"3121":{"name":"Gymnazia","parents":["Služby pro obyvatelstvo","Vzdělávání a školské služby","Střední vzdělávání a vzdělávání v konzervatořích"]},
	"3122":{"name":"Střední odborné školy","parents":["Služby pro obyvatelstvo","Vzdělávání a školské služby","Střední vzdělávání a vzdělávání v konzervatořích"]},
	"3123":{"name":"Střední školy poskytující střední vzdělání s výučním listem","parents":["Služby pro obyvatelstvo","Vzdělávání a školské služby","Střední vzdělávání a vzdělávání v konzervatořích"]},
	"3124":{"name":"Střední školy a konzervatoře pro žáky se speciálními vzdělávacími potřebami","parents":["Služby pro obyvatelstvo","Vzdělávání a školské služby","Střední vzdělávání a vzdělávání v konzervatořích"]},
	"3125":{"name":"Střediska praktického vyučování a školní hospodářství","parents":["Služby pro obyvatelstvo","Vzdělávání a školské služby","Střední vzdělávání a vzdělávání v konzervatořích"]},
	"3126":{"name":"Konzervatoře","parents":["Služby pro obyvatelstvo","Vzdělávání a školské služby","Střední vzdělávání a vzdělávání v konzervatořích"]},
	"3127":{"name":"Střední školy","parents":["Služby pro obyvatelstvo","Vzdělávání a školské služby","Střední vzdělávání a vzdělávání v konzervatořích"]},
	"3128":{"name":"Sportovní školy - gymnázia","parents":["Služby pro obyvatelstvo","Vzdělávání a školské služby","Střední vzdělávání a vzdělávání v konzervatořích"]},
	"3129":{"name":"Ostatní zařízení středního vzdělávání","parents":["Služby pro obyvatelstvo","Vzdělávání a školské služby","Střední vzdělávání a vzdělávání v konzervatořích"]},
	"3131":{"name":"Výchovné ústavy a dětské domovy se školou","parents":["Služby pro obyvatelstvo","Vzdělávání a školské služby","Školská zařízení pro výkon ústavní a ochranné výchovy"]},
	"3132":{"name":"Diagnostické ústavy","parents":["Služby pro obyvatelstvo","Vzdělávání a školské služby","Školská zařízení pro výkon ústavní a ochranné výchovy"]},
	"3133":{"name":"Dětské domovy","parents":["Služby pro obyvatelstvo","Vzdělávání a školské služby","Školská zařízení pro výkon ústavní a ochranné výchovy"]},
	"3139":{"name":"Ostatní školská zařízení pro výkon ústavní a ochranné výchovy","parents":["Služby pro obyvatelstvo","Vzdělávání a školské služby","Školská zařízení pro výkon ústavní a ochranné výchovy"]},
	"3141":{"name":"Školní stravování","parents":["Služby pro obyvatelstvo","Vzdělávání a školské služby","Ostatní zařízení související s výchovou a vzděláváním mládeže"]},
	"3143":{"name":"Školní družiny a kluby","parents":["Služby pro obyvatelstvo","Vzdělávání a školské služby","Ostatní zařízení související s výchovou a vzděláváním mládeže"]},
	"3144":{"name":"Školy v přírodě","parents":["Služby pro obyvatelstvo","Vzdělávání a školské služby","Ostatní zařízení související s výchovou a vzděláváním mládeže"]},
	"3145":{"name":"Internáty","parents":["Služby pro obyvatelstvo","Vzdělávání a školské služby","Ostatní zařízení související s výchovou a vzděláváním mládeže"]},
	"3146":{"name":"Zařízení výchovného poradenství","parents":["Služby pro obyvatelstvo","Vzdělávání a školské služby","Ostatní zařízení související s výchovou a vzděláváním mládeže"]},
	"3147":{"name":"Domovy mládeže","parents":["Služby pro obyvatelstvo","Vzdělávání a školské služby","Ostatní zařízení související s výchovou a vzděláváním mládeže"]},
	"3148":{"name":"Střediska výchovné péče","parents":["Služby pro obyvatelstvo","Vzdělávání a školské služby","Ostatní zařízení související s výchovou a vzděláváním mládeže"]},
	"3149":{"name":"Ostatní zařízení související s výchovou a vzděláváním mládeže","parents":["Služby pro obyvatelstvo","Vzdělávání a školské služby","Ostatní zařízení související s výchovou a vzděláváním mládeže"]},
	"3150":{"name":"Vyšší odborné školy","parents":["Služby pro obyvatelstvo","Vzdělávání a školské služby","Vyšší odborné vzdělávání"]},
	"3211":{"name":"Vysoké školy","parents":["Služby pro obyvatelstvo","Vzdělávání a školské služby","Vysokoškolské vzdělávání"]},
	"3212":{"name":"Výzkum, vývoj a inovace na vysokých školách","parents":["Služby pro obyvatelstvo","Vzdělávání a školské služby","Vysokoškolské vzdělávání"]},
	"3213":{"name":"Bakalářské studium","parents":["Služby pro obyvatelstvo","Vzdělávání a školské služby","Vysokoškolské vzdělávání"]},
	"3214":{"name":"Magisterské a doktorské studium","parents":["Služby pro obyvatelstvo","Vzdělávání a školské služby","Vysokoškolské vzdělávání"]},
	"3221":{"name":"Vysokoškolské koleje a menzy","parents":["Služby pro obyvatelstvo","Vzdělávání a školské služby","Zařízení související s vysokoškolským vzděláváním"]},
	"3229":{"name":"Ostatní zařízení související s vysokoškolským vzděláváním","parents":["Služby pro obyvatelstvo","Vzdělávání a školské služby","Zařízení související s vysokoškolským vzděláváním"]},
	"3231":{"name":"Základní umělecké školy","parents":["Služby pro obyvatelstvo","Vzdělávání a školské služby","Základní umělecké, jazykové a zájmové vzdělávání"]},
	"3232":{"name":"Jazykové školy s právem státní jazykové zkoušky","parents":["Služby pro obyvatelstvo","Vzdělávání a školské služby","Základní umělecké, jazykové a zájmové vzdělávání"]},
	"3233":{"name":"Střediska volného času","parents":["Služby pro obyvatelstvo","Vzdělávání a školské služby","Základní umělecké, jazykové a zájmové vzdělávání"]},
	"3239":{"name":"Záležitosti zájmového vzdělávání jinde nezařazené","parents":["Služby pro obyvatelstvo","Vzdělávání a školské služby","Základní umělecké, jazykové a zájmové vzdělávání"]},
	"3261":{"name":"Činnost ústředního orgánu státní správy ve vzdělávání","parents":["Služby pro obyvatelstvo","Vzdělávání a školské služby","Správa ve vzdělávání"]},
	"3262":{"name":"Činnost ostatních orgánů státní správy ve vzdělávání","parents":["Služby pro obyvatelstvo","Vzdělávání a školské služby","Správa ve vzdělávání"]},
	"3269":{"name":"Ostatní správa ve vzdělávání jinde nezařazená","parents":["Služby pro obyvatelstvo","Vzdělávání a školské služby","Správa ve vzdělávání"]},
	"3280":{"name":"Výzkum školství a vzdělávání","parents":["Služby pro obyvatelstvo","Vzdělávání a školské služby","Výzkum školství a vzdělávání"]},
	"3291":{"name":"Mezinárodní spolupráce ve vzdělávání","parents":["Služby pro obyvatelstvo","Vzdělávání a školské služby","Ostatní činnost a nespecifikované výdaje"]},
	"3292":{"name":"Vzdělávání národnostních menšin a multikulturní výchova","parents":["Služby pro obyvatelstvo","Vzdělávání a školské služby","Ostatní činnost a nespecifikované výdaje"]},
	"3293":{"name":"Vzdělávací akce k integraci Romů","parents":["Služby pro obyvatelstvo","Vzdělávání a školské služby","Ostatní činnost a nespecifikované výdaje"]},
	"3294":{"name":"Zařízení pro další vzdělávání pedagogických pracovníků","parents":["Služby pro obyvatelstvo","Vzdělávání a školské služby","Ostatní činnost a nespecifikované výdaje"]},
	"3299":{"name":"Ostatní záležitosti vzdělávání","parents":["Služby pro obyvatelstvo","Vzdělávání a školské služby","Ostatní činnost a nespecifikované výdaje"]},
	"3311":{"name":"Divadelní činnost","parents":["Služby pro obyvatelstvo","Kultura, církve a sdělovací prostředky","Kultura"]},
	"3312":{"name":"Hudební činnost","parents":["Služby pro obyvatelstvo","Kultura, církve a sdělovací prostředky","Kultura"]},
	"3313":{"name":"Filmová tvorba, distribuce, kina a shromažďování audiovizuálních archiválií","parents":["Služby pro obyvatelstvo","Kultura, církve a sdělovací prostředky","Kultura"]},
	"3314":{"name":"Činnosti knihovnické","parents":["Služby pro obyvatelstvo","Kultura, církve a sdělovací prostředky","Kultura"]},
	"3315":{"name":"Činnosti muzeí a galerií","parents":["Služby pro obyvatelstvo","Kultura, církve a sdělovací prostředky","Kultura"]},
	"3316":{"name":"Vydavatelská činnost","parents":["Služby pro obyvatelstvo","Kultura, církve a sdělovací prostředky","Kultura"]},
	"3317":{"name":"Výstavní činnosti v kultuře","parents":["Služby pro obyvatelstvo","Kultura, církve a sdělovací prostředky","Kultura"]},
	"3319":{"name":"Ostatní záležitosti kultury","parents":["Služby pro obyvatelstvo","Kultura, církve a sdělovací prostředky","Kultura"]},
	"3321":{"name":"Činnosti památkových ústavů, hradů a zámků","parents":["Služby pro obyvatelstvo","Kultura, církve a sdělovací prostředky","Ochrana památek a péče o kulturní dědictví a národní a historické povědomí"]},
	"3322":{"name":"Zachování a obnova kulturních památek","parents":["Služby pro obyvatelstvo","Kultura, církve a sdělovací prostředky","Ochrana památek a péče o kulturní dědictví a národní a historické povědomí"]},
	"3324":{"name":"Výkup předmětů kulturní hodnoty","parents":["Služby pro obyvatelstvo","Kultura, církve a sdělovací prostředky","Ochrana památek a péče o kulturní dědictví a národní a historické povědomí"]},
	"3325":{"name":"Pražský hrad","parents":["Služby pro obyvatelstvo","Kultura, církve a sdělovací prostředky","Ochrana památek a péče o kulturní dědictví a národní a historické povědomí"]},
	"3326":{"name":"Pořízení, zachování a obnova hodnot místního kulturního, národního a historického povědomí","parents":["Služby pro obyvatelstvo","Kultura, církve a sdělovací prostředky","Ochrana památek a péče o kulturní dědictví a národní a historické povědomí"]},
	"3329":{"name":"Ostatní záležitosti ochrany památek a péče o kulturní dědictví","parents":["Služby pro obyvatelstvo","Kultura, církve a sdělovací prostředky","Ochrana památek a péče o kulturní dědictví a národní a historické povědomí"]},
	"3330":{"name":"Činnosti registrovaných církví a náboženských společností","parents":["Služby pro obyvatelstvo","Kultura, církve a sdělovací prostředky","Činnosti registrovaných církví a náboženských společností"]},
	"3341":{"name":"Rozhlas a televize","parents":["Služby pro obyvatelstvo","Kultura, církve a sdělovací prostředky","Sdělovací prostředky"]},
	"3349":{"name":"Ostatní záležitosti sdělovacích prostředků","parents":["Služby pro obyvatelstvo","Kultura, církve a sdělovací prostředky","Sdělovací prostředky"]},
	"3361":{"name":"Činnost ústředního orgánu státní správy v oblasti kultury a církví","parents":["Služby pro obyvatelstvo","Kultura, církve a sdělovací prostředky","Správa v oblasti kultury, církví a sdělovacích prostředků"]},
	"3362":{"name":"Činnost ostatních orgánů státní správy v oblasti kultury, církví a sdělovacích prostředků","parents":["Služby pro obyvatelstvo","Kultura, církve a sdělovací prostředky","Správa v oblasti kultury, církví a sdělovacích prostředků"]},
	"3369":{"name":"Ostatní správa v oblasti kultury, církví a sdělovacích prostředků","parents":["Služby pro obyvatelstvo","Kultura, církve a sdělovací prostředky","Správa v oblasti kultury, církví a sdělovacích prostředků"]},
	"3380":{"name":"Výzkum a vývoj v oblasti kultury, církví a sdělovacích prostředků","parents":["Služby pro obyvatelstvo","Kultura, církve a sdělovací prostředky","Výzkum a vývoj v oblasti kultury, církví a sdělovacích prostředků"]},
	"3391":{"name":"Mezinárodní spolupráce v kultuře, církvích a sdělovacích prostředcích","parents":["Služby pro obyvatelstvo","Kultura, církve a sdělovací prostředky","Ostatní činnosti v záležitostech kultury, církví a sdělovacích prostředků"]},
	"3392":{"name":"Zájmová činnost v kultuře","parents":["Služby pro obyvatelstvo","Kultura, církve a sdělovací prostředky","Ostatní činnosti v záležitostech kultury, církví a sdělovacích prostředků"]},
	"3399":{"name":"Ostatní záležitosti kultury, církví a sdělovacích prostředků","parents":["Služby pro obyvatelstvo","Kultura, církve a sdělovací prostředky","Ostatní činnosti v záležitostech kultury, církví a sdělovacích prostředků"]},
	"3411":{"name":"Státní sportovní reprezentace","parents":["Služby pro obyvatelstvo","Tělovýchova a zájmová činnost","Tělovýchova"]},
	"3412":{"name":"Sportovní zařízení v majetku obcí","parents":["Služby pro obyvatelstvo","Tělovýchova a zájmová činnost","Tělovýchova"]},
	"3419":{"name":"Ostatní tělovýchovná činnost","parents":["Služby pro obyvatelstvo","Tělovýchova a zájmová činnost","Tělovýchova"]},
	"3421":{"name":"Využití volného času dětí a mládeže","parents":["Služby pro obyvatelstvo","Tělovýchova a zájmová činnost","Zájmová činnost a rekreace"]},
	"3429":{"name":"Ostatní zájmová činnost a rekreace","parents":["Služby pro obyvatelstvo","Tělovýchova a zájmová činnost","Zájmová činnost a rekreace"]},
	"3480":{"name":"Výzkum v oblasti tělovýchovy, zájmové činnosti a rekreace","parents":["Služby pro obyvatelstvo","Tělovýchova a zájmová činnost","Výzkum v oblasti tělovýchovy, zájmové činnosti a rekreace"]},
	"3511":{"name":"Všeobecná ambulantní péče","parents":["Služby pro obyvatelstvo","Zdravotnictví","Ambulantní péče"]},
	"3512":{"name":"Stomatologická péče","parents":["Služby pro obyvatelstvo","Zdravotnictví","Ambulantní péče"]},
	"3513":{"name":"Lékařská služba první pomoci","parents":["Služby pro obyvatelstvo","Zdravotnictví","Ambulantní péče"]},
	"3514":{"name":"Transfúzní služba a tkáňová zařízení","parents":["Služby pro obyvatelstvo","Zdravotnictví","Ambulantní péče"]},
	"3515":{"name":"Specializovaná ambulantní zdravotní péče","parents":["Služby pro obyvatelstvo","Zdravotnictví","Ambulantní péče"]},
	"3516":{"name":"Péče v mateřství","parents":["Služby pro obyvatelstvo","Zdravotnictví","Ambulantní péče"]},
	"3519":{"name":"Ostatní ambulantní péče","parents":["Služby pro obyvatelstvo","Zdravotnictví","Ambulantní péče"]},
	"3521":{"name":"Fakultní nemocnice","parents":["Služby pro obyvatelstvo","Zdravotnictví","Ústavní péče"]},
	"3522":{"name":"Ostatní nemocnice","parents":["Služby pro obyvatelstvo","Zdravotnictví","Ústavní péče"]},
	"3523":{"name":"Odborné léčebné ústavy","parents":["Služby pro obyvatelstvo","Zdravotnictví","Ústavní péče"]},
	"3524":{"name":"Léčebny dlouhodobě nemocných","parents":["Služby pro obyvatelstvo","Zdravotnictví","Ústavní péče"]},
	"3525":{"name":"Hospice","parents":["Služby pro obyvatelstvo","Zdravotnictví","Ústavní péče"]},
	"3526":{"name":"Lázeňské léčebny, ozdravovny, sanatoria","parents":["Služby pro obyvatelstvo","Zdravotnictví","Ústavní péče"]},
	"3527":{"name":"Vysoce specializovaná pracoviště a jednooborové zařízení lůžkové péče","parents":["Služby pro obyvatelstvo","Zdravotnictví","Ústavní péče"]},
	"3529":{"name":"Ostatní ústavní péče","parents":["Služby pro obyvatelstvo","Zdravotnictví","Ústavní péče"]},
	"3531":{"name":"Hygienická služba a ochrana veřejného zdraví","parents":["Služby pro obyvatelstvo","Zdravotnictví","Zvláštní zdravotnická zařízení a služby pro zdravotnictví"]},
	"3532":{"name":"Lékárenská služba (léky, protézy a přístroje pro užití vně zdravotnických zařízení)","parents":["Služby pro obyvatelstvo","Zdravotnictví","Zvláštní zdravotnická zařízení a služby pro zdravotnictví"]},
	"3533":{"name":"Zdravotnická záchranná služba","parents":["Služby pro obyvatelstvo","Zdravotnictví","Zvláštní zdravotnická zařízení a služby pro zdravotnictví"]},
	"3534":{"name":"Doprava ve zdravotnictví","parents":["Služby pro obyvatelstvo","Zdravotnictví","Zvláštní zdravotnická zařízení a služby pro zdravotnictví"]},
	"3539":{"name":"Ostatní zdravotnická zařízení a služby pro zdravotnictví","parents":["Služby pro obyvatelstvo","Zdravotnictví","Zvláštní zdravotnická zařízení a služby pro zdravotnictví"]},
	"3541":{"name":"Prevence před drogami, alkoholem, nikotinem aj. závislostmi","parents":["Služby pro obyvatelstvo","Zdravotnictví","Zdravotnické programy"]},
	"3542":{"name":"Prevence HIV/AIDS","parents":["Služby pro obyvatelstvo","Zdravotnictví","Zdravotnické programy"]},
	"3543":{"name":"Pomoc zdravotně postiženým a chronicky nemocným","parents":["Služby pro obyvatelstvo","Zdravotnictví","Zdravotnické programy"]},
	"3544":{"name":"Národní program zdraví","parents":["Služby pro obyvatelstvo","Zdravotnictví","Zdravotnické programy"]},
	"3545":{"name":"Programy paliativní péče","parents":["Služby pro obyvatelstvo","Zdravotnictví","Zdravotnické programy"]},
	"3549":{"name":"Ostatní speciální zdravotnická péče","parents":["Služby pro obyvatelstvo","Zdravotnictví","Zdravotnické programy"]},
	"3561":{"name":"Činnost ústředního orgánu státní správy ve zdravotnictví","parents":["Služby pro obyvatelstvo","Zdravotnictví","Správa ve zdravotnictví"]},
	"3562":{"name":"Činnost ostatních orgánů státní správy ve zdravotnictví","parents":["Služby pro obyvatelstvo","Zdravotnictví","Správa ve zdravotnictví"]},
	"3569":{"name":"Ostatní správa ve zdravotnictví jinde nezařazená","parents":["Služby pro obyvatelstvo","Zdravotnictví","Správa ve zdravotnictví"]},
	"3581":{"name":"Organizace výzkumu a střediska vědeckých informací","parents":["Služby pro obyvatelstvo","Zdravotnictví","Výzkum a vývoj ve zdravotnictví"]},
	"3589":{"name":"Ostatní výzkum a vývoj ve zdravotnictví","parents":["Služby pro obyvatelstvo","Zdravotnictví","Výzkum a vývoj ve zdravotnictví"]},
	"3591":{"name":"Mezinárodní spolupráce ve zdravotnictví","parents":["Služby pro obyvatelstvo","Zdravotnictví","Ostatní činnost ve zdravotnictví"]},
	"3592":{"name":"Další vzdělávání pracovníků ve zdravotnictví","parents":["Služby pro obyvatelstvo","Zdravotnictví","Ostatní činnost ve zdravotnictví"]},
	"3599":{"name":"Ostatní činnost ve zdravotnictví","parents":["Služby pro obyvatelstvo","Zdravotnictví","Ostatní činnost ve zdravotnictví"]},
	"3611":{"name":"Podpora individuální bytové výstavby","parents":["Služby pro obyvatelstvo","Bydlení, komunální služby a územní rozvoj","Rozvoj bydlení a bytové hospodářství"]},
	"3612":{"name":"Bytové hospodářství","parents":["Služby pro obyvatelstvo","Bydlení, komunální služby a územní rozvoj","Rozvoj bydlení a bytové hospodářství"]},
	"3613":{"name":"Nebytové hospodářství","parents":["Služby pro obyvatelstvo","Bydlení, komunální služby a územní rozvoj","Rozvoj bydlení a bytové hospodářství"]},
	"3614":{"name":"Bytové služby pro vlastní zaměstnance","parents":["Služby pro obyvatelstvo","Bydlení, komunální služby a územní rozvoj","Rozvoj bydlení a bytové hospodářství"]},
	"3615":{"name":"Podpora stavebního spoření a hypotečních úvěrů","parents":["Služby pro obyvatelstvo","Bydlení, komunální služby a územní rozvoj","Rozvoj bydlení a bytové hospodářství"]},
	"3619":{"name":"Ostatní rozvoj bydlení a bytového hospodářství","parents":["Služby pro obyvatelstvo","Bydlení, komunální služby a územní rozvoj","Rozvoj bydlení a bytové hospodářství"]},
	"3631":{"name":"Veřejné osvětlení","parents":["Služby pro obyvatelstvo","Bydlení, komunální služby a územní rozvoj","Komunální služby a územní rozvoj"]},
	"3632":{"name":"Pohřebnictví","parents":["Služby pro obyvatelstvo","Bydlení, komunální služby a územní rozvoj","Komunální služby a územní rozvoj"]},
	"3633":{"name":"Výstavba a údržba místních inženýrských sítí","parents":["Služby pro obyvatelstvo","Bydlení, komunální služby a územní rozvoj","Komunální služby a územní rozvoj"]},
	"3634":{"name":"Lokální zásobování teplem","parents":["Služby pro obyvatelstvo","Bydlení, komunální služby a územní rozvoj","Komunální služby a územní rozvoj"]},
	"3635":{"name":"Územní plánování","parents":["Služby pro obyvatelstvo","Bydlení, komunální služby a územní rozvoj","Komunální služby a územní rozvoj"]},
	"3636":{"name":"Územní rozvoj","parents":["Služby pro obyvatelstvo","Bydlení, komunální služby a územní rozvoj","Komunální služby a územní rozvoj"]},
	"3639":{"name":"Komunální služby a územní rozvoj jinde nezařazené","parents":["Služby pro obyvatelstvo","Bydlení, komunální služby a územní rozvoj","Komunální služby a územní rozvoj"]},
	"3661":{"name":"Činnost ústředního orgánu státní správy v oblasti bydlení, komunálních služeb a územního rozvoje","parents":["Služby pro obyvatelstvo","Bydlení, komunální služby a územní rozvoj","Správa v oblasti bydlení, komunálních služeb a územního rozvoje"]},
	"3662":{"name":"Činnost ostatních orgánů státní správy v oblasti bydlení, komunálních služeb a územního rozvoje","parents":["Služby pro obyvatelstvo","Bydlení, komunální služby a územní rozvoj","Správa v oblasti bydlení, komunálních služeb a územního rozvoje"]},
	"3669":{"name":"Ostatní správa v oblasti v oblasti bydlení, komunálních služeb a územního rozvoje jinde nezařazená","parents":["Služby pro obyvatelstvo","Bydlení, komunální služby a územní rozvoj","Správa v oblasti bydlení, komunálních služeb a územního rozvoje"]},
	"3680":{"name":"Výzkum a vývoj v oblasti bydlení, komunálních služeb a územního rozvoje","parents":["Služby pro obyvatelstvo","Bydlení, komunální služby a územní rozvoj","Výzkum a vývoj v oblasti bydlení, komunálních služeb a územního rozvoje"]},
	"3691":{"name":"Mezinárodní spolupráce v oblasti bydlení, komunálních služeb a územního rozvoje","parents":["Služby pro obyvatelstvo","Bydlení, komunální služby a územní rozvoj","Ostatní činnost v oblasti bydlení, komunálních služeb a územního rozvoje"]},
	"3699":{"name":"Ostatní záležitosti bydlení, komunálních služeb a územního rozvoje","parents":["Služby pro obyvatelstvo","Bydlení, komunální služby a územní rozvoj","Ostatní činnost v oblasti bydlení, komunálních služeb a územního rozvoje"]},
	"3711":{"name":"Odstraňování tuhých emisí","parents":["Služby pro obyvatelstvo","Ochrana životního prostředí","Ochrana ovzduší a klimatu"]},
	"3712":{"name":"Odstraňování plynných emisí","parents":["Služby pro obyvatelstvo","Ochrana životního prostředí","Ochrana ovzduší a klimatu"]},
	"3713":{"name":"Změny technologií vytápění","parents":["Služby pro obyvatelstvo","Ochrana životního prostředí","Ochrana ovzduší a klimatu"]},
	"3714":{"name":"Opatření ke snižování produkce skleníkových plynů a plynů poškozujících ozónovou vrstvu","parents":["Služby pro obyvatelstvo","Ochrana životního prostředí","Ochrana ovzduší a klimatu"]},
	"3715":{"name":"Změny výrobních technologií za účelem výrazného odstranění emisí","parents":["Služby pro obyvatelstvo","Ochrana životního prostředí","Ochrana ovzduší a klimatu"]},
	"3716":{"name":"Monitoring ochrany ovzduší","parents":["Služby pro obyvatelstvo","Ochrana životního prostředí","Ochrana ovzduší a klimatu"]},
	"3719":{"name":"Ostatní činnosti k ochraně ovzduší","parents":["Služby pro obyvatelstvo","Ochrana životního prostředí","Ochrana ovzduší a klimatu"]},
	"3721":{"name":"Sběr a svoz nebezpečných odpadů","parents":["Služby pro obyvatelstvo","Ochrana životního prostředí","Nakládání s odpady"]},
	"3722":{"name":"Sběr a svoz komunálních odpadů","parents":["Služby pro obyvatelstvo","Ochrana životního prostředí","Nakládání s odpady"]},
	"3723":{"name":"Sběr a svoz ostatních odpadů (jiných než nebezpečných a komunálních)","parents":["Služby pro obyvatelstvo","Ochrana životního prostředí","Nakládání s odpady"]},
	"3724":{"name":"Využívání a zneškodňování nebezpečných odpadů","parents":["Služby pro obyvatelstvo","Ochrana životního prostředí","Nakládání s odpady"]},
	"3725":{"name":"Využívání a zneškodňování komunálních odpadů","parents":["Služby pro obyvatelstvo","Ochrana životního prostředí","Nakládání s odpady"]},
	"3726":{"name":"Využívání a zneškodňování ostatních odpadů","parents":["Služby pro obyvatelstvo","Ochrana životního prostředí","Nakládání s odpady"]},
	"3727":{"name":"Prevence vzniku odpadů","parents":["Služby pro obyvatelstvo","Ochrana životního prostředí","Nakládání s odpady"]},
	"3728":{"name":"Monitoring nakládání s odpady","parents":["Služby pro obyvatelstvo","Ochrana životního prostředí","Nakládání s odpady"]},
	"3729":{"name":"Ostatní nakládání s odpady","parents":["Služby pro obyvatelstvo","Ochrana životního prostředí","Nakládání s odpady"]},
	"3731":{"name":"Ochrana půdy a podzemní vody proti znečišťujícím infiltracím","parents":["Služby pro obyvatelstvo","Ochrana životního prostředí","Ochrana a sanace půdy a podzemní vody"]},
	"3732":{"name":"Dekontaminace půd a čištění spodní vody","parents":["Služby pro obyvatelstvo","Ochrana životního prostředí","Ochrana a sanace půdy a podzemní vody"]},
	"3733":{"name":"Monitoring půdy a podzemní vody","parents":["Služby pro obyvatelstvo","Ochrana životního prostředí","Ochrana a sanace půdy a podzemní vody"]},
	"3734":{"name":"Předcházení a sanace zasolení půd","parents":["Služby pro obyvatelstvo","Ochrana životního prostředí","Ochrana a sanace půdy a podzemní vody"]},
	"3739":{"name":"Ostatní ochrana půdy a spodní vody","parents":["Služby pro obyvatelstvo","Ochrana životního prostředí","Ochrana a sanace půdy a podzemní vody"]},
	"3741":{"name":"Ochrana druhů a stanovišť","parents":["Služby pro obyvatelstvo","Ochrana životního prostředí","Ochrana přírody a krajiny"]},
	"3742":{"name":"Chráněné části přírody","parents":["Služby pro obyvatelstvo","Ochrana životního prostředí","Ochrana přírody a krajiny"]},
	"3743":{"name":"Rekultivace půdy v důsledku těžební a důlní činnosti, po skládkách odpadů apod.","parents":["Služby pro obyvatelstvo","Ochrana životního prostředí","Ochrana přírody a krajiny"]},
	"3744":{"name":"Protierozní, protilavinová a protipožární ochrana","parents":["Služby pro obyvatelstvo","Ochrana životního prostředí","Ochrana přírody a krajiny"]},
	"3745":{"name":"Péče o vzhled obcí a veřejnou zeleň","parents":["Služby pro obyvatelstvo","Ochrana životního prostředí","Ochrana přírody a krajiny"]},
	"3749":{"name":"Ostatní činnosti k ochraně přírody a krajiny","parents":["Služby pro obyvatelstvo","Ochrana životního prostředí","Ochrana přírody a krajiny"]},
	"3751":{"name":"Konstrukce a uplatnění protihlukových zařízení (protihlukové stěny a bariéry, okna, zapouzdření strojů apod.)","parents":["Služby pro obyvatelstvo","Ochrana životního prostředí","Omezování hluku a vibrací"]},
	"3753":{"name":"Monitoring ke zjišťování úrovně hluku a vibrací","parents":["Služby pro obyvatelstvo","Ochrana životního prostředí","Omezování hluku a vibrací"]},
	"3759":{"name":"Ostatní činnosti k omezení hluku a vibrací","parents":["Služby pro obyvatelstvo","Ochrana životního prostředí","Omezování hluku a vibrací"]},
	"3761":{"name":"Činnost ústředního orgánu státní správy v ochraně životního prostředí","parents":["Služby pro obyvatelstvo","Ochrana životního prostředí","Správa v ochraně životního prostředí"]},
	"3762":{"name":"Činnost ostatních orgánů státní správy v ochraně životního prostředí","parents":["Služby pro obyvatelstvo","Ochrana životního prostředí","Správa v ochraně životního prostředí"]},
	"3769":{"name":"Ostatní správa v ochraně životního prostředí","parents":["Služby pro obyvatelstvo","Ochrana životního prostředí","Správa v ochraně životního prostředí"]},
	"3771":{"name":"Protiradonová opatření","parents":["Služby pro obyvatelstvo","Ochrana životního prostředí","Ochrana proti záření"]},
	"3772":{"name":"Přeprava a nakládání s vysoce radioaktivním odpadem","parents":["Služby pro obyvatelstvo","Ochrana životního prostředí","Ochrana proti záření"]},
	"3773":{"name":"Monitoring k zajišťování úrovně radioaktivního záření","parents":["Služby pro obyvatelstvo","Ochrana životního prostředí","Ochrana proti záření"]},
	"3779":{"name":"Ostatní činnosti k ochraně proti záření","parents":["Služby pro obyvatelstvo","Ochrana životního prostředí","Ochrana proti záření"]},
	"3780":{"name":"Výzkum životního prostředí","parents":["Služby pro obyvatelstvo","Ochrana životního prostředí","Výzkum životního prostředí"]},
	"3791":{"name":"Mezinárodní spolupráce v životním prostředí","parents":["Služby pro obyvatelstvo","Ochrana životního prostředí","Ostatní činnosti v životním prostředí"]},
	"3792":{"name":"Ekologická výchova a osvěta","parents":["Služby pro obyvatelstvo","Ochrana životního prostředí","Ostatní činnosti v životním prostředí"]},
	"3793":{"name":"Ekologie v dopravě","parents":["Služby pro obyvatelstvo","Ochrana životního prostředí","Ostatní činnosti v životním prostředí"]},
	"3799":{"name":"Ostatní ekologické záležitosti","parents":["Služby pro obyvatelstvo","Ochrana životního prostředí","Ostatní činnosti v životním prostředí"]},
	"3801":{"name":"Akademie věd České republiky","parents":["Služby pro obyvatelstvo","Ostatní výzkum a vývoj","Ostatní výzkum a vývoj"]},
	"3802":{"name":"Grantová agentura České republiky","parents":["Služby pro obyvatelstvo","Ostatní výzkum a vývoj","Ostatní výzkum a vývoj"]},
	"3803":{"name":"Technologická agentura České republiky","parents":["Služby pro obyvatelstvo","Ostatní výzkum a vývoj","Ostatní výzkum a vývoj"]},
	"3809":{"name":"Ostatní výzkum a vývoj odvětvově nespecifikovaný","parents":["Služby pro obyvatelstvo","Ostatní výzkum a vývoj","Ostatní výzkum a vývoj"]},
	"3900":{"name":"Ostatní činnosti související se službami pro obyvatelstvo","parents":["Služby pro obyvatelstvo","Ostatní činnosti související se službami pro obyvatelstvo","Ostatní činnosti související se službami pro obyvatelstvo"]},
	"4111":{"name":"Starobní důchody","parents":["Sociální věci a politika zaměstnanosti","Dávky a podpory v sociálním zabezpečení","Dávky důchodového pojištění"]},
	"4112":{"name":"Invalidní důchody pro invaliditu třetího stupně","parents":["Sociální věci a politika zaměstnanosti","Dávky a podpory v sociálním zabezpečení","Dávky důchodového pojištění"]},
	"4113":{"name":"Invalidní důchody pro invaliditu druhého stupně","parents":["Sociální věci a politika zaměstnanosti","Dávky a podpory v sociálním zabezpečení","Dávky důchodového pojištění"]},
	"4114":{"name":"Vdovské důchody","parents":["Sociální věci a politika zaměstnanosti","Dávky a podpory v sociálním zabezpečení","Dávky důchodového pojištění"]},
	"4115":{"name":"Vdovecké důchody","parents":["Sociální věci a politika zaměstnanosti","Dávky a podpory v sociálním zabezpečení","Dávky důchodového pojištění"]},
	"4116":{"name":"Sirotčí důchody","parents":["Sociální věci a politika zaměstnanosti","Dávky a podpory v sociálním zabezpečení","Dávky důchodového pojištění"]},
	"4117":{"name":"Invalidní důchody pro invaliditu prvního stupně","parents":["Sociální věci a politika zaměstnanosti","Dávky a podpory v sociálním zabezpečení","Dávky důchodového pojištění"]},
	"4119":{"name":"Ostatní dávky důchodového pojištění","parents":["Sociální věci a politika zaměstnanosti","Dávky a podpory v sociálním zabezpečení","Dávky důchodového pojištění"]},
	"4121":{"name":"Nemocenské","parents":["Sociální věci a politika zaměstnanosti","Dávky a podpory v sociálním zabezpečení","Dávky nemocenského pojištění"]},
	"4122":{"name":"Ošetřovné","parents":["Sociální věci a politika zaměstnanosti","Dávky a podpory v sociálním zabezpečení","Dávky nemocenského pojištění"]},
	"4123":{"name":"Vyrovnávací příspěvek v těhotenství a mateřství","parents":["Sociální věci a politika zaměstnanosti","Dávky a podpory v sociálním zabezpečení","Dávky nemocenského pojištění"]},
	"4124":{"name":"Peněžitá pomoc v mateřství","parents":["Sociální věci a politika zaměstnanosti","Dávky a podpory v sociálním zabezpečení","Dávky nemocenského pojištění"]},
	"4129":{"name":"Dávky nemocenského pojištění jinde nezařazené","parents":["Sociální věci a politika zaměstnanosti","Dávky a podpory v sociálním zabezpečení","Dávky nemocenského pojištění"]},
	"4131":{"name":"Přídavek na dítě","parents":["Sociální věci a politika zaměstnanosti","Dávky a podpory v sociálním zabezpečení","Dávky státní sociální podpory a dávky pěstounské péče"]},
	"4132":{"name":"Sociální příplatek","parents":["Sociální věci a politika zaměstnanosti","Dávky a podpory v sociálním zabezpečení","Dávky státní sociální podpory a dávky pěstounské péče"]},
	"4133":{"name":"Porodné","parents":["Sociální věci a politika zaměstnanosti","Dávky a podpory v sociálním zabezpečení","Dávky státní sociální podpory a dávky pěstounské péče"]},
	"4134":{"name":"Rodičovský příspěvek","parents":["Sociální věci a politika zaměstnanosti","Dávky a podpory v sociálním zabezpečení","Dávky státní sociální podpory a dávky pěstounské péče"]},
	"4136":{"name":"Dávky pěstounské péče","parents":["Sociální věci a politika zaměstnanosti","Dávky a podpory v sociálním zabezpečení","Dávky státní sociální podpory a dávky pěstounské péče"]},
	"4138":{"name":"Pohřebné","parents":["Sociální věci a politika zaměstnanosti","Dávky a podpory v sociálním zabezpečení","Dávky státní sociální podpory a dávky pěstounské péče"]},
	"4141":{"name":"Příspěvek na bydlení","parents":["Sociální věci a politika zaměstnanosti","Dávky a podpory v sociálním zabezpečení","Dávky státní sociální podpory a dávky pěstounské péče"]},
	"4142":{"name":"Příspěvek na školní pomůcky","parents":["Sociální věci a politika zaměstnanosti","Dávky a podpory v sociálním zabezpečení","Dávky státní sociální podpory a dávky pěstounské péče"]},
	"4149":{"name":"Dávky státní sociální podpory jinde nezařazené","parents":["Sociální věci a politika zaměstnanosti","Dávky a podpory v sociálním zabezpečení","Dávky státní sociální podpory a dávky pěstounské péče"]},
	"4151":{"name":"Odchodné","parents":["Sociální věci a politika zaměstnanosti","Dávky a podpory v sociálním zabezpečení","Zvláštní sociální dávky příslušníků ozbrojených sil při skončení služebního poměru"]},
	"4152":{"name":"Výsluhový příspěvek","parents":["Sociální věci a politika zaměstnanosti","Dávky a podpory v sociálním zabezpečení","Zvláštní sociální dávky příslušníků ozbrojených sil při skončení služebního poměru"]},
	"4153":{"name":"Úmrtné a příspěvek na pohřeb příslušníka","parents":["Sociální věci a politika zaměstnanosti","Dávky a podpory v sociálním zabezpečení","Zvláštní sociální dávky příslušníků ozbrojených sil při skončení služebního poměru"]},
	"4154":{"name":"Odbytné","parents":["Sociální věci a politika zaměstnanosti","Dávky a podpory v sociálním zabezpečení","Zvláštní sociální dávky příslušníků ozbrojených sil při skončení služebního poměru"]},
	"4159":{"name":"Ostatní sociální dávky příslušníků ozbrojených sil při skončení služebního poměru","parents":["Sociální věci a politika zaměstnanosti","Dávky a podpory v sociálním zabezpečení","Zvláštní sociální dávky příslušníků ozbrojených sil při skončení služebního poměru"]},
	"4161":{"name":"Úrazový příplatek","parents":["Sociální věci a politika zaměstnanosti","Dávky a podpory v sociálním zabezpečení","Dávky úrazového pojištění"]},
	"4162":{"name":"Úrazové vyrovnání","parents":["Sociální věci a politika zaměstnanosti","Dávky a podpory v sociálním zabezpečení","Dávky úrazového pojištění"]},
	"4163":{"name":"Bolestné","parents":["Sociální věci a politika zaměstnanosti","Dávky a podpory v sociálním zabezpečení","Dávky úrazového pojištění"]},
	"4164":{"name":"Příspěvek za ztížení společenského uplatnění","parents":["Sociální věci a politika zaměstnanosti","Dávky a podpory v sociálním zabezpečení","Dávky úrazového pojištění"]},
	"4165":{"name":"Náhrada nákladů spojených s léčením","parents":["Sociální věci a politika zaměstnanosti","Dávky a podpory v sociálním zabezpečení","Dávky úrazového pojištění"]},
	"4166":{"name":"Náhrada nákladů spojených s pohřbem","parents":["Sociální věci a politika zaměstnanosti","Dávky a podpory v sociálním zabezpečení","Dávky úrazového pojištění"]},
	"4167":{"name":"Jednorázový příspěvek pozůstalému","parents":["Sociální věci a politika zaměstnanosti","Dávky a podpory v sociálním zabezpečení","Dávky úrazového pojištění"]},
	"4168":{"name":"Úrazová renta pozůstalého","parents":["Sociální věci a politika zaměstnanosti","Dávky a podpory v sociálním zabezpečení","Dávky úrazového pojištění"]},
	"4169":{"name":"Ostatní dávky úrazového pojištění","parents":["Sociální věci a politika zaměstnanosti","Dávky a podpory v sociálním zabezpečení","Dávky úrazového pojištění"]},
	"4171":{"name":"Příspěvek na živobytí","parents":["Sociální věci a politika zaměstnanosti","Dávky a podpory v sociálním zabezpečení","Dávky pomoci v hmotné nouzi"]},
	"4172":{"name":"Doplatek na bydlení","parents":["Sociální věci a politika zaměstnanosti","Dávky a podpory v sociálním zabezpečení","Dávky pomoci v hmotné nouzi"]},
	"4173":{"name":"Mimořádná okamžitá pomoc","parents":["Sociální věci a politika zaměstnanosti","Dávky a podpory v sociálním zabezpečení","Dávky pomoci v hmotné nouzi"]},
	"4177":{"name":"Mimořádná okamžitá pomoc osobám ohroženým sociálním vyloučením","parents":["Sociální věci a politika zaměstnanosti","Dávky a podpory v sociálním zabezpečení","Dávky pomoci v hmotné nouzi"]},
	"4179":{"name":"Ostatní dávky sociální pomoci","parents":["Sociální věci a politika zaměstnanosti","Dávky a podpory v sociálním zabezpečení","Dávky pomoci v hmotné nouzi"]},
	"4182":{"name":"Příspěvek na zvláštní pomůcky","parents":["Sociální věci a politika zaměstnanosti","Dávky a podpory v sociálním zabezpečení","Dávky osobám se zdravotním postižením"]},
	"4183":{"name":"Příspěvek na úpravu a provoz bezbariérového bytu","parents":["Sociální věci a politika zaměstnanosti","Dávky a podpory v sociálním zabezpečení","Dávky osobám se zdravotním postižením"]},
	"4184":{"name":"Příspěvky na zakoupení, opravu a zvláštní úpravu motorového vozidla","parents":["Sociální věci a politika zaměstnanosti","Dávky a podpory v sociálním zabezpečení","Dávky osobám se zdravotním postižením"]},
	"4185":{"name":"Příspěvek na provoz motorového vozidla","parents":["Sociální věci a politika zaměstnanosti","Dávky a podpory v sociálním zabezpečení","Dávky osobám se zdravotním postižením"]},
	"4186":{"name":"Příspěvek na individuální dopravu","parents":["Sociální věci a politika zaměstnanosti","Dávky a podpory v sociálním zabezpečení","Dávky osobám se zdravotním postižením"]},
	"4187":{"name":"Příspěvek na mobilitu","parents":["Sociální věci a politika zaměstnanosti","Dávky a podpory v sociálním zabezpečení","Dávky osobám se zdravotním postižením"]},
	"4188":{"name":"Příspěvek na zvláštní pomůcku","parents":["Sociální věci a politika zaměstnanosti","Dávky a podpory v sociálním zabezpečení","Dávky osobám se zdravotním postižením"]},
	"4189":{"name":"Ostatní dávky zdravotně postiženým občanům","parents":["Sociální věci a politika zaměstnanosti","Dávky a podpory v sociálním zabezpečení","Dávky osobám se zdravotním postižením"]},
	"4191":{"name":"Státní příspěvky na důchodové připojištění","parents":["Sociální věci a politika zaměstnanosti","Dávky a podpory v sociálním zabezpečení","Ostatní dávky povahy sociálního zabezpečení"]},
	"4192":{"name":"Úrokové příspěvky mladým manželstvím","parents":["Sociální věci a politika zaměstnanosti","Dávky a podpory v sociálním zabezpečení","Ostatní dávky povahy sociálního zabezpečení"]},
	"4193":{"name":"Dávky a odškodnění válečným veteránům a perzekvovaným osobám","parents":["Sociální věci a politika zaměstnanosti","Dávky a podpory v sociálním zabezpečení","Ostatní dávky povahy sociálního zabezpečení"]},
	"4194":{"name":"Zvýšení důchodů pro bezmocnost","parents":["Sociální věci a politika zaměstnanosti","Dávky a podpory v sociálním zabezpečení","Ostatní dávky povahy sociálního zabezpečení"]},
	"4195":{"name":"Příspěvek na péči","parents":["Sociální věci a politika zaměstnanosti","Dávky a podpory v sociálním zabezpečení","Ostatní dávky povahy sociálního zabezpečení"]},
	"4199":{"name":"Ostatní dávky povahy sociálního zabezpečení jinde nezařazené","parents":["Sociální věci a politika zaměstnanosti","Dávky a podpory v sociálním zabezpečení","Ostatní dávky povahy sociálního zabezpečení"]},
	"4210":{"name":"Podpory v nezaměstnanosti","parents":["Sociální věci a politika zaměstnanosti","Politika zaměstnanosti","Podpory v nezaměstnanosti"]},
	"4221":{"name":"Rekvalifikace","parents":["Sociální věci a politika zaměstnanosti","Politika zaměstnanosti","Aktivní politika zaměstnanosti"]},
	"4222":{"name":"Veřejně prospěšné práce","parents":["Sociální věci a politika zaměstnanosti","Politika zaměstnanosti","Aktivní politika zaměstnanosti"]},
	"4223":{"name":"Společensky účelná pracovní místa","parents":["Sociální věci a politika zaměstnanosti","Politika zaměstnanosti","Aktivní politika zaměstnanosti"]},
	"4225":{"name":"Podpora zaměstnanosti zdravotně postižených občanů","parents":["Sociální věci a politika zaměstnanosti","Politika zaměstnanosti","Aktivní politika zaměstnanosti"]},
	"4226":{"name":"Ostatní podpora zaměstnanosti","parents":["Sociální věci a politika zaměstnanosti","Politika zaměstnanosti","Aktivní politika zaměstnanosti"]},
	"4227":{"name":"Cílené programy k řešení zaměstnanosti","parents":["Sociální věci a politika zaměstnanosti","Politika zaměstnanosti","Aktivní politika zaměstnanosti"]},
	"4229":{"name":"Aktivní politika zaměstnanosti jinde nezařazená","parents":["Sociální věci a politika zaměstnanosti","Politika zaměstnanosti","Aktivní politika zaměstnanosti"]},
	"4230":{"name":"Ochrana zaměstnanců při platební neschopnosti zaměstnavatelů","parents":["Sociální věci a politika zaměstnanosti","Politika zaměstnanosti","Ochrana zaměstnanců při platební neschopnosti zaměstnavatelů"]},
	"4240":{"name":"Příspěvek zaměstnavatelům zaměstnávajícím více než 50% občanů se změněnou pracovní schopností","parents":["Sociální věci a politika zaměstnanosti","Politika zaměstnanosti","Zaměstnávání zdravotně postižených občanů"]},
	"4250":{"name":"Příspěvky na sociální důsledky restrukturalizace","parents":["Sociální věci a politika zaměstnanosti","Politika zaměstnanosti","Příspěvky na sociální důsledky restrukturalizace"]},
	"4280":{"name":"Výzkum a vývoj v politice zaměstnanosti","parents":["Sociální věci a politika zaměstnanosti","Politika zaměstnanosti","Výzkum a vývoj v politice zaměstnanosti"]},
	"4311":{"name":"Základní sociální poradenství","parents":["Sociální věci a politika zaměstnanosti","Sociální služby a společné činnosti v sociálním zabezpečení a politice zaměstnanosti","Sociální poradenství"]},
	"4312":{"name":"Odborné sociální poradenství","parents":["Sociální věci a politika zaměstnanosti","Sociální služby a společné činnosti v sociálním zabezpečení a politice zaměstnanosti","Sociální poradenství"]},
	"4319":{"name":"Ostatní výdaje související se sociálním poradenstvím","parents":["Sociální věci a politika zaměstnanosti","Sociální služby a společné činnosti v sociálním zabezpečení a politice zaměstnanosti","Sociální poradenství"]},
	"4324":{"name":"Zařízení pro děti vyžadující okamžitou pomoc","parents":["Sociální věci a politika zaměstnanosti","Sociální služby a společné činnosti v sociálním zabezpečení a politice zaměstnanosti","Sociální péče a pomoc dětem a mládeži"]},
	"4329":{"name":"Ostatní sociální péče a pomoc dětem a mládeži","parents":["Sociální věci a politika zaměstnanosti","Sociální služby a společné činnosti v sociálním zabezpečení a politice zaměstnanosti","Sociální péče a pomoc dětem a mládeži"]},
	"4333":{"name":"Domovy-penzióny pro matky s dětmi","parents":["Sociální věci a politika zaměstnanosti","Sociální služby a společné činnosti v sociálním zabezpečení a politice zaměstnanosti","Sociální péče a pomoc manželství a rodinám"]},
	"4334":{"name":"Pečovatelská služba pro rodinu a děti","parents":["Sociální věci a politika zaměstnanosti","Sociální služby a společné činnosti v sociálním zabezpečení a politice zaměstnanosti","Sociální péče a pomoc manželství a rodinám"]},
	"4339":{"name":"Ostatní sociální péče a pomoc rodině a manželství","parents":["Sociální věci a politika zaměstnanosti","Sociální služby a společné činnosti v sociálním zabezpečení a politice zaměstnanosti","Sociální péče a pomoc manželství a rodinám"]},
	"4341":{"name":"Sociální pomoc osobám v hmotné nouzi a občanům sociálně nepřizpůsobivým","parents":["Sociální věci a politika zaměstnanosti","Sociální služby a společné činnosti v sociálním zabezpečení a politice zaměstnanosti","Sociální rehabilitace a ostatní sociální péče a pomoc"]},
	"4342":{"name":"Sociální péče a pomoc přistěhovalcům a vybraným etnikům","parents":["Sociální věci a politika zaměstnanosti","Sociální služby a společné činnosti v sociálním zabezpečení a politice zaměstnanosti","Sociální rehabilitace a ostatní sociální péče a pomoc"]},
	"4343":{"name":"Sociální pomoc osobám v souvislosti s živelní pohromou nebo požárem","parents":["Sociální věci a politika zaměstnanosti","Sociální služby a společné činnosti v sociálním zabezpečení a politice zaměstnanosti","Sociální rehabilitace a ostatní sociální péče a pomoc"]},
	"4344":{"name":"Sociální poradenství pro staré občany","parents":["Sociální věci a politika zaměstnanosti","Sociální služby a společné činnosti v sociálním zabezpečení a politice zaměstnanosti","Sociální rehabilitace a ostatní sociální péče a pomoc"]},
	"4345":{"name":"Centra sociálně rehabilitačních služeb","parents":["Sociální věci a politika zaměstnanosti","Sociální služby a společné činnosti v sociálním zabezpečení a politice zaměstnanosti","Sociální rehabilitace a ostatní sociální péče a pomoc"]},
	"4349":{"name":"Ostatní sociální péče a pomoc ostatním skupinám obyvatelstva","parents":["Sociální věci a politika zaměstnanosti","Sociální služby a společné činnosti v sociálním zabezpečení a politice zaměstnanosti","Sociální rehabilitace a ostatní sociální péče a pomoc"]},
	"4350":{"name":"Domovy pro seniory","parents":["Sociální věci a politika zaměstnanosti","Sociální služby a společné činnosti v sociálním zabezpečení a politice zaměstnanosti","Služby sociální péče"]},
	"4351":{"name":"Osobní asistence, pečovatelská služba a podpora samostatného bydlení","parents":["Sociální věci a politika zaměstnanosti","Sociální služby a společné činnosti v sociálním zabezpečení a politice zaměstnanosti","Služby sociální péče"]},
	"4352":{"name":"Tísňová péče","parents":["Sociální věci a politika zaměstnanosti","Sociální služby a společné činnosti v sociálním zabezpečení a politice zaměstnanosti","Služby sociální péče"]},
	"4353":{"name":"Průvodcovské a předčitatelské služby","parents":["Sociální věci a politika zaměstnanosti","Sociální služby a společné činnosti v sociálním zabezpečení a politice zaměstnanosti","Služby sociální péče"]},
	"4354":{"name":"Chráněné bydlení","parents":["Sociální věci a politika zaměstnanosti","Sociální služby a společné činnosti v sociálním zabezpečení a politice zaměstnanosti","Služby sociální péče"]},
	"4355":{"name":"Týdenní stacionáře","parents":["Sociální věci a politika zaměstnanosti","Sociální služby a společné činnosti v sociálním zabezpečení a politice zaměstnanosti","Služby sociální péče"]},
	"4356":{"name":"Denní stacionáře a centra denních služeb","parents":["Sociální věci a politika zaměstnanosti","Sociální služby a společné činnosti v sociálním zabezpečení a politice zaměstnanosti","Služby sociální péče"]},
	"4357":{"name":"Domovy pro osoby se zdravotním postižením a domovy se zvláštním režimem","parents":["Sociální věci a politika zaměstnanosti","Sociální služby a společné činnosti v sociálním zabezpečení a politice zaměstnanosti","Služby sociální péče"]},
	"4358":{"name":"Sociální služby poskytované ve zdravotnických zařízeních ústavní péče","parents":["Sociální věci a politika zaměstnanosti","Sociální služby a společné činnosti v sociálním zabezpečení a politice zaměstnanosti","Služby sociální péče"]},
	"4359":{"name":"Ostatní služby a činnosti v oblasti sociální péče","parents":["Sociální věci a politika zaměstnanosti","Sociální služby a společné činnosti v sociálním zabezpečení a politice zaměstnanosti","Služby sociální péče"]},
	"4361":{"name":"Činnost ústředního orgánu státní správy v sociálním zabezpečení, politice zaměstnanosti a rodinné politice","parents":["Sociální věci a politika zaměstnanosti","Sociální služby a společné činnosti v sociálním zabezpečení a politice zaměstnanosti","Správa v sociálním zabezpečení a politice zaměstnanosti"]},
	"4362":{"name":"Činnost ostatních orgánů státní správy v sociálním zabezpečení","parents":["Sociální věci a politika zaměstnanosti","Sociální služby a společné činnosti v sociálním zabezpečení a politice zaměstnanosti","Správa v sociálním zabezpečení a politice zaměstnanosti"]},
	"4363":{"name":"Ostatní orgány státní správy v oblasti politiky zaměstnanosti","parents":["Sociální věci a politika zaměstnanosti","Sociální služby a společné činnosti v sociálním zabezpečení a politice zaměstnanosti","Správa v sociálním zabezpečení a politice zaměstnanosti"]},
	"4369":{"name":"Ostatní správa v sociálním zabezpečení a politice zaměstnanosti","parents":["Sociální věci a politika zaměstnanosti","Sociální služby a společné činnosti v sociálním zabezpečení a politice zaměstnanosti","Správa v sociálním zabezpečení a politice zaměstnanosti"]},
	"4371":{"name":"Raná péče a sociálně aktivizační služby pro rodiny s dětmi","parents":["Sociální věci a politika zaměstnanosti","Sociální služby a společné činnosti v sociálním zabezpečení a politice zaměstnanosti","Služby sociální prevence"]},
	"4372":{"name":"Krizová pomoc","parents":["Sociální věci a politika zaměstnanosti","Sociální služby a společné činnosti v sociálním zabezpečení a politice zaměstnanosti","Služby sociální prevence"]},
	"4373":{"name":"Domy na půl cesty","parents":["Sociální věci a politika zaměstnanosti","Sociální služby a společné činnosti v sociálním zabezpečení a politice zaměstnanosti","Služby sociální prevence"]},
	"4374":{"name":"Azylové domy, nízkoprahová denní centra a noclehárny","parents":["Sociální věci a politika zaměstnanosti","Sociální služby a společné činnosti v sociálním zabezpečení a politice zaměstnanosti","Služby sociální prevence"]},
	"4375":{"name":"Nízkoprahová zařízení pro děti a mládež","parents":["Sociální věci a politika zaměstnanosti","Sociální služby a společné činnosti v sociálním zabezpečení a politice zaměstnanosti","Služby sociální prevence"]},
	"4376":{"name":"Služby následné péče, terapeutické komunity a kontaktní centra","parents":["Sociální věci a politika zaměstnanosti","Sociální služby a společné činnosti v sociálním zabezpečení a politice zaměstnanosti","Služby sociální prevence"]},
	"4377":{"name":"Sociálně terapeutické dílny","parents":["Sociální věci a politika zaměstnanosti","Sociální služby a společné činnosti v sociálním zabezpečení a politice zaměstnanosti","Služby sociální prevence"]},
	"4378":{"name":"Terénní programy","parents":["Sociální věci a politika zaměstnanosti","Sociální služby a společné činnosti v sociálním zabezpečení a politice zaměstnanosti","Služby sociální prevence"]},
	"4379":{"name":"Ostatní služby a činnosti v oblasti sociální prevence","parents":["Sociální věci a politika zaměstnanosti","Sociální služby a společné činnosti v sociálním zabezpečení a politice zaměstnanosti","Služby sociální prevence"]},
	"4380":{"name":"Výzkum v sociálním zabezpečení a politice zaměstnanosti","parents":["Sociální věci a politika zaměstnanosti","Sociální služby a společné činnosti v sociálním zabezpečení a politice zaměstnanosti","Výzkum v sociálním zabezpečení a politice zaměstnanosti"]},
	"4391":{"name":"Mezinárodní spolupráce v sociálním zabezpečení a podpoře zaměstnanosti","parents":["Sociální věci a politika zaměstnanosti","Sociální služby a společné činnosti v sociálním zabezpečení a politice zaměstnanosti","Ostatní činnost a nespecifikované výdaje"]},
	"4392":{"name":"Inspekce poskytování sociálních služeb","parents":["Sociální věci a politika zaměstnanosti","Sociální služby a společné činnosti v sociálním zabezpečení a politice zaměstnanosti","Ostatní činnost a nespecifikované výdaje"]},
	"4399":{"name":"Ostatní záležitosti sociálních věcí a politiky zaměstnanosti","parents":["Sociální věci a politika zaměstnanosti","Sociální služby a společné činnosti v sociálním zabezpečení a politice zaměstnanosti","Ostatní činnost a nespecifikované výdaje"]},
	"5111":{"name":"Armáda","parents":["Bezpečnost státu a právní ochrana","Obrana","Vojenská obrana"]},
	"5112":{"name":"Ostatní ozbrojené síly","parents":["Bezpečnost státu a právní ochrana","Obrana","Vojenská obrana"]},
	"5113":{"name":"Bezpečnostní složky ozbrojených sil","parents":["Bezpečnost státu a právní ochrana","Obrana","Vojenská obrana"]},
	"5119":{"name":"Podpůrné složky ozbrojených sil","parents":["Bezpečnost státu a právní ochrana","Obrana","Vojenská obrana"]},
	"5161":{"name":"Činnost ústředního orgánu státní správy ve vojenské obraně","parents":["Bezpečnost státu a právní ochrana","Obrana","Státní správa ve vojenské obraně"]},
	"5162":{"name":"Činnost ostatních orgánů státní správy ve vojenské obraně","parents":["Bezpečnost státu a právní ochrana","Obrana","Státní správa ve vojenské obraně"]},
	"5169":{"name":"Ostatní správa ve vojenské obraně","parents":["Bezpečnost státu a právní ochrana","Obrana","Státní správa ve vojenské obraně"]},
	"5171":{"name":"Zabezpečení potřeb ozbrojených sil","parents":["Bezpečnost státu a právní ochrana","Obrana","Zabezpečení potřeb ozbrojených sil"]},
	"5172":{"name":"Operační příprava státního území","parents":["Bezpečnost státu a právní ochrana","Obrana","Zabezpečení potřeb ozbrojených sil"]},
	"5179":{"name":"Ostatní činnosti pro zabezpečení potřeb ozbrojených sil","parents":["Bezpečnost státu a právní ochrana","Obrana","Zabezpečení potřeb ozbrojených sil"]},
	"5180":{"name":"Výzkum a vývoj v oblasti obrany","parents":["Bezpečnost státu a právní ochrana","Obrana","Výzkum a vývoj v oblasti obrany"]},
	"5191":{"name":"Mezinárodní spolupráce v obraně","parents":["Bezpečnost státu a právní ochrana","Obrana","Ostatní záležitosti obrany"]},
	"5192":{"name":"Zahraniční vojenská pomoc","parents":["Bezpečnost státu a právní ochrana","Obrana","Ostatní záležitosti obrany"]},
	"5199":{"name":"Ostatní záležitosti obrany","parents":["Bezpečnost státu a právní ochrana","Obrana","Ostatní záležitosti obrany"]},
	"5211":{"name":"Civilní ochrana-vojenská část","parents":["Bezpečnost státu a právní ochrana","Civilní připravenost na krizové stavy","Ochrana obyvatelstva"]},
	"5212":{"name":"Ochrana obyvatelstva","parents":["Bezpečnost státu a právní ochrana","Civilní připravenost na krizové stavy","Ochrana obyvatelstva"]},
	"5219":{"name":"Ostatní záležitosti ochrany obyvatelstva","parents":["Bezpečnost státu a právní ochrana","Civilní připravenost na krizové stavy","Ochrana obyvatelstva"]},
	"5220":{"name":"Hospodářská opatření pro krizové stavy","parents":["Bezpečnost státu a právní ochrana","Civilní připravenost na krizové stavy","Hospodářská opatření pro krizové stavy"]},
	"5261":{"name":"Státní správa v oblasti hospodářských opatření pro krizové stavy a v oblasti krizového řízení","parents":["Bezpečnost státu a právní ochrana","Civilní připravenost na krizové stavy","Státní správa v oblasti hospodářských opatření"]},
	"5262":{"name":"Činnost ostatních orgánů státní správy v oblasti civilního nouzového hospodářství","parents":["Bezpečnost státu a právní ochrana","Civilní připravenost na krizové stavy","Státní správa v oblasti hospodářských opatření"]},
	"5269":{"name":"Ostatní správa v oblasti hospodářských opatření pro krizové stavy","parents":["Bezpečnost státu a právní ochrana","Civilní připravenost na krizové stavy","Státní správa v oblasti hospodářských opatření"]},
	"5271":{"name":"Činnost orgánů krizového řízení na ústřední úrovni a dalších správních úřadů v oblasti krizového řízení","parents":["Bezpečnost státu a právní ochrana","Civilní připravenost na krizové stavy","Krizové řízení"]},
	"5272":{"name":"Činnost orgánů krizového řízení na územní úrovni a dalších územních správních úřadů v oblasti krizového řízení","parents":["Bezpečnost státu a právní ochrana","Civilní připravenost na krizové stavy","Krizové řízení"]},
	"5273":{"name":"Ostatní správa v oblasti krizového řízení","parents":["Bezpečnost státu a právní ochrana","Civilní připravenost na krizové stavy","Krizové řízení"]},
	"5274":{"name":"Podpora krizového řízení a nouzového plánování","parents":["Bezpečnost státu a právní ochrana","Civilní připravenost na krizové stavy","Krizové řízení"]},
	"5279":{"name":"Záležitosti krizového řízení jinde nezařazené","parents":["Bezpečnost státu a právní ochrana","Civilní připravenost na krizové stavy","Krizové řízení"]},
	"5281":{"name":"Výzkum a vývoj v oblasti ochrany obyvatelstva","parents":["Bezpečnost státu a právní ochrana","Civilní připravenost na krizové stavy","Výzkum a vývoj v oblasti civilní připravenosti na krizové stavy"]},
	"5289":{"name":"Výzkum a vývoj v oblasti krizového řízení","parents":["Bezpečnost státu a právní ochrana","Civilní připravenost na krizové stavy","Výzkum a vývoj v oblasti civilní připravenosti na krizové stavy"]},
	"5291":{"name":"Mezinárodní spolupráce v oblasti krizového řízení","parents":["Bezpečnost státu a právní ochrana","Civilní připravenost na krizové stavy","Ostatní záležitosti civilní připravenosti pro krizové stavy"]},
	"5292":{"name":"Poskytnutí vzájemné zahraniční pomoci podle mezinárodních smluv","parents":["Bezpečnost státu a právní ochrana","Civilní připravenost na krizové stavy","Ostatní záležitosti civilní připravenosti pro krizové stavy"]},
	"5299":{"name":"Ostatní záležitosti civilní připravenosti na krizové stavy","parents":["Bezpečnost státu a právní ochrana","Civilní připravenost na krizové stavy","Ostatní záležitosti civilní připravenosti pro krizové stavy"]},
	"5311":{"name":"Bezpečnost a veřejný pořádek","parents":["Bezpečnost státu a právní ochrana","Bezpečnost a veřejný pořádek","Bezpečnost a veřejný pořádek"]},
	"5316":{"name":"Činnost ústředního orgánu státní správy v oblasti bezpečnosti a veřejného pořádku","parents":["Bezpečnost státu a právní ochrana","Bezpečnost a veřejný pořádek","Bezpečnost a veřejný pořádek"]},
	"5317":{"name":"Hraniční přechody","parents":["Bezpečnost státu a právní ochrana","Bezpečnost a veřejný pořádek","Bezpečnost a veřejný pořádek"]},
	"5319":{"name":"Ostatní záležitosti bezpečnosti a veřejného pořádku","parents":["Bezpečnost státu a právní ochrana","Bezpečnost a veřejný pořádek","Bezpečnost a veřejný pořádek"]},
	"5380":{"name":"Výzkum týkající se bezpečnosti a veřejného pořádku","parents":["Bezpečnost státu a právní ochrana","Bezpečnost a veřejný pořádek","Výzkum týkající se bezpečnosti a veřejného pořádku"]},
	"5391":{"name":"Mezinárodní spolupráce v oblasti bezpečnosti a veřejného pořádku","parents":["Bezpečnost státu a právní ochrana","Bezpečnost a veřejný pořádek","Ostatní záležitosti bezpečnosti a veřejného pořádku"]},
	"5399":{"name":"Ostatní záležitosti bezpečnosti,veřejného pořádku","parents":["Bezpečnost státu a právní ochrana","Bezpečnost a veřejný pořádek","Ostatní záležitosti bezpečnosti a veřejného pořádku"]},
	"5410":{"name":"Ústavní soud","parents":["Bezpečnost státu a právní ochrana","Právní ochrana","Ústavní soudnictví"]},
	"5420":{"name":"Soudy","parents":["Bezpečnost státu a právní ochrana","Právní ochrana","Soudnictví"]},
	"5430":{"name":"Státní zastupitelství","parents":["Bezpečnost státu a právní ochrana","Právní ochrana","Státní zastupitelství"]},
	"5441":{"name":"Činnost Generálního ředitelství Vězeňské služby a věznic","parents":["Bezpečnost státu a právní ochrana","Právní ochrana","Vězeňství"]},
	"5442":{"name":"Ostatní správa ve vězeňství","parents":["Bezpečnost státu a právní ochrana","Právní ochrana","Vězeňství"]},
	"5449":{"name":"Ostatní záležitosti vězeňství","parents":["Bezpečnost státu a právní ochrana","Právní ochrana","Vězeňství"]},
	"5450":{"name":"Činnost probační a mediační služby","parents":["Bezpečnost státu a právní ochrana","Právní ochrana","Probační a mediační služba"]},
	"5461":{"name":"Činnost ústředního orgánu státní správy v oblasti právní ochrany","parents":["Bezpečnost státu a právní ochrana","Právní ochrana","Správa v oblasti právní ochrany"]},
	"5462":{"name":"Činnost ostatních orgánů státní správy v oblasti právní ochrany","parents":["Bezpečnost státu a právní ochrana","Právní ochrana","Správa v oblasti právní ochrany"]},
	"5469":{"name":"Ostatní správa v oblasti právní ochrany","parents":["Bezpečnost státu a právní ochrana","Právní ochrana","Správa v oblasti právní ochrany"]},
	"5470":{"name":"Kancelář Veřejného ochránce práv","parents":["Bezpečnost státu a právní ochrana","Právní ochrana","Veřejná ochrana"]},
	"5471":{"name":"Kancelář finančního arbitra","parents":["Bezpečnost státu a právní ochrana","Právní ochrana","Veřejná ochrana"]},
	"5480":{"name":"Výzkum v oblasti právní ochrany","parents":["Bezpečnost státu a právní ochrana","Právní ochrana","Výzkum v oblasti právní ochrany"]},
	"5491":{"name":"Mezinárodní spolupráce v oblasti právní ochrany","parents":["Bezpečnost státu a právní ochrana","Právní ochrana","Ostatní záležitosti právní ochrany"]},
	"5499":{"name":"Ostatní záležitosti právní ochrany","parents":["Bezpečnost státu a právní ochrana","Právní ochrana","Ostatní záležitosti právní ochrany"]},
	"5511":{"name":"Požární ochrana - profesionální část","parents":["Bezpečnost státu a právní ochrana","Požární ochrana a integrovaný záchranný systém","Požární ochrana"]},
	"5512":{"name":"Požární ochrana - dobrovolná část","parents":["Bezpečnost státu a právní ochrana","Požární ochrana a integrovaný záchranný systém","Požární ochrana"]},
	"5517":{"name":"Vzdělávací a technická zařízení požární ochrany","parents":["Bezpečnost státu a právní ochrana","Požární ochrana a integrovaný záchranný systém","Požární ochrana"]},
	"5519":{"name":"Ostatní záležitosti požární ochrany","parents":["Bezpečnost státu a právní ochrana","Požární ochrana a integrovaný záchranný systém","Požární ochrana"]},
	"5521":{"name":"Operační a informační střediska integrovaného záchranného systému.","parents":["Bezpečnost státu a právní ochrana","Požární ochrana a integrovaný záchranný systém","Ostatní složky a činnosti integrovaného záchranného systému"]},
	"5522":{"name":"Ostatní činnosti v integrovaném záchranném systému","parents":["Bezpečnost státu a právní ochrana","Požární ochrana a integrovaný záchranný systém","Ostatní složky a činnosti integrovaného záchranného systému"]},
	"5529":{"name":"Ostatní složky a činnosti integrovaného záchranného systému","parents":["Bezpečnost státu a právní ochrana","Požární ochrana a integrovaný záchranný systém","Ostatní složky a činnosti integrovaného záchranného systému"]},
	"5561":{"name":"Činnost ústředního orgánu státní správy v požární ochraně","parents":["Bezpečnost státu a právní ochrana","Požární ochrana a integrovaný záchranný systém","Státní správa v požární ochraně a intergovaném záchranném systému"]},
	"5562":{"name":"Činnost ústředních orgánů státní správy v integrovaném záchranném systému","parents":["Bezpečnost státu a právní ochrana","Požární ochrana a integrovaný záchranný systém","Státní správa v požární ochraně a intergovaném záchranném systému"]},
	"5563":{"name":"Činnost ostatních orgánů státní správy v integrovaném záchranném systému","parents":["Bezpečnost státu a právní ochrana","Požární ochrana a integrovaný záchranný systém","Státní správa v požární ochraně a intergovaném záchranném systému"]},
	"5580":{"name":"Výzkum a vývoj v požární ochraně a integrovaném záchranném systému","parents":["Bezpečnost státu a právní ochrana","Požární ochrana a integrovaný záchranný systém","Výzkum a vývoj v požární ochraně a integrovaném záchranném systému"]},
	"5591":{"name":"Mezinárodní spolupráce v oblasti požární ochrany a integrovaném záchranném systému","parents":["Bezpečnost státu a právní ochrana","Požární ochrana a integrovaný záchranný systém","Ostatní záležitosti požární ochrany a integrovaného záchranného systému"]},
	"5592":{"name":"Poskytnutí vzájemné zahraniční pomoci podle mezinárodních smluv","parents":["Bezpečnost státu a právní ochrana","Požární ochrana a integrovaný záchranný systém","Ostatní záležitosti požární ochrany a integrovaného záchranného systému"]},
	"5599":{"name":"Ostatní záležitosti požární ochrany a integrovaného záchranného systému","parents":["Bezpečnost státu a právní ochrana","Požární ochrana a integrovaný záchranný systém","Ostatní záležitosti požární ochrany a integrovaného záchranného systému"]},
	"6111":{"name":"Parlament","parents":["Všeobecná veřejná správa a služby","Státní moc, státní správa, územní samospráva a politické strany","Zastupitelské orgány a volby"]},
	"6112":{"name":"Zastupitelstva obcí","parents":["Všeobecná veřejná správa a služby","Státní moc, státní správa, územní samospráva a politické strany","Zastupitelské orgány a volby"]},
	"6113":{"name":"Zastupitelstva krajů","parents":["Všeobecná veřejná správa a služby","Státní moc, státní správa, územní samospráva a politické strany","Zastupitelské orgány a volby"]},
	"6114":{"name":"Volby do Parlamentu ČR","parents":["Všeobecná veřejná správa a služby","Státní moc, státní správa, územní samospráva a politické strany","Zastupitelské orgány a volby"]},
	"6115":{"name":"Volby do zastupitelstev územních samosprávných celků","parents":["Všeobecná veřejná správa a služby","Státní moc, státní správa, územní samospráva a politické strany","Zastupitelské orgány a volby"]},
	"6116":{"name":"Celostátní referendum","parents":["Všeobecná veřejná správa a služby","Státní moc, státní správa, územní samospráva a politické strany","Zastupitelské orgány a volby"]},
	"6117":{"name":"Volby do Evropského parlamentu","parents":["Všeobecná veřejná správa a služby","Státní moc, státní správa, územní samospráva a politické strany","Zastupitelské orgány a volby"]},
	"6118":{"name":"Volba prezidenta republiky","parents":["Všeobecná veřejná správa a služby","Státní moc, státní správa, územní samospráva a politické strany","Zastupitelské orgány a volby"]},
	"6119":{"name":"Ostatní zastupitelské orgány a volby","parents":["Všeobecná veřejná správa a služby","Státní moc, státní správa, územní samospráva a politické strany","Zastupitelské orgány a volby"]},
	"6120":{"name":"Kancelář prezidenta republiky","parents":["Všeobecná veřejná správa a služby","Státní moc, státní správa, územní samospráva a politické strany","Kancelář prezidenta republiky"]},
	"6130":{"name":"Nejvyšší kontrolní úřad","parents":["Všeobecná veřejná správa a služby","Státní moc, státní správa, územní samospráva a politické strany","Nejvyšší kontrolní úřad"]},
	"6141":{"name":"Ústřední orgány vnitřní státní správy a jejich dislokovaná pracoviště (nezařazené v jiných funkcích)","parents":["Všeobecná veřejná správa a služby","Státní moc, státní správa, územní samospráva a politické strany","Všeobecná vnitřní státní správa (nezařazená v jiných funkcích)"]},
	"6142":{"name":"Finanční správa","parents":["Všeobecná veřejná správa a služby","Státní moc, státní správa, územní samospráva a politické strany","Všeobecná vnitřní státní správa (nezařazená v jiných funkcích)"]},
	"6143":{"name":"Celní správa","parents":["Všeobecná veřejná správa a služby","Státní moc, státní správa, územní samospráva a politické strany","Všeobecná vnitřní státní správa (nezařazená v jiných funkcích)"]},
	"6145":{"name":"Úřad vlády","parents":["Všeobecná veřejná správa a služby","Státní moc, státní správa, územní samospráva a politické strany","Všeobecná vnitřní státní správa (nezařazená v jiných funkcích)"]},
	"6146":{"name":"Český statistický úřad","parents":["Všeobecná veřejná správa a služby","Státní moc, státní správa, územní samospráva a politické strany","Všeobecná vnitřní státní správa (nezařazená v jiných funkcích)"]},
	"6148":{"name":"Plánování a statistika","parents":["Všeobecná veřejná správa a služby","Státní moc, státní správa, územní samospráva a politické strany","Všeobecná vnitřní státní správa (nezařazená v jiných funkcích)"]},
	"6149":{"name":"Ostatní všeobecná vnitřní správa jinde nezařazená","parents":["Všeobecná veřejná správa a služby","Státní moc, státní správa, územní samospráva a politické strany","Všeobecná vnitřní státní správa (nezařazená v jiných funkcích)"]},
	"6151":{"name":"Činnost ústředního orgánu státní správy v zahraniční službě","parents":["Všeobecná veřejná správa a služby","Státní moc, státní správa, územní samospráva a politické strany","Zahraniční služba a záležitosti (nezařazené v jiných funkcích)"]},
	"6152":{"name":"Zastupitelství a stálé mise ČR v zahraničí","parents":["Všeobecná veřejná správa a služby","Státní moc, státní správa, územní samospráva a politické strany","Zahraniční služba a záležitosti (nezařazené v jiných funkcích)"]},
	"6153":{"name":"Ostatní účast v mezinárodních vládních organizacích","parents":["Všeobecná veřejná správa a služby","Státní moc, státní správa, územní samospráva a politické strany","Zahraniční služba a záležitosti (nezařazené v jiných funkcích)"]},
	"6159":{"name":"Zahraniční služba a záležitosti jinde nezařazené","parents":["Všeobecná veřejná správa a služby","Státní moc, státní správa, územní samospráva a politické strany","Zahraniční služba a záležitosti (nezařazené v jiných funkcích)"]},
	"6171":{"name":"Činnost místní správy","parents":["Všeobecná veřejná správa a služby","Státní moc, státní správa, územní samospráva a politické strany","Regionální a místní správa"]},
	"6172":{"name":"Činnost regionální správy","parents":["Všeobecná veřejná správa a služby","Státní moc, státní správa, územní samospráva a politické strany","Regionální a místní správa"]},
	"6173":{"name":"Místní referendum","parents":["Všeobecná veřejná správa a služby","Státní moc, státní správa, územní samospráva a politické strany","Regionální a místní správa"]},
	"6174":{"name":"Činnost regionálních rad","parents":["Všeobecná veřejná správa a služby","Státní moc, státní správa, územní samospráva a politické strany","Regionální a místní správa"]},
	"6180":{"name":"Výzkum ve státní správě a samosprávě","parents":["Všeobecná veřejná správa a služby","Státní moc, státní správa, územní samospráva a politické strany","Výzkum ve státní správě a samosprávě"]},
	"6190":{"name":"Politické strany a hnutí","parents":["Všeobecná veřejná správa a služby","Státní moc, státní správa, územní samospráva a politické strany","Politické strany a hnutí"]},
	"6211":{"name":"Archivní činnost","parents":["Všeobecná veřejná správa a služby","Jiné veřejné služby a činnosti","Ostatní veřejné služby"]},
	"6219":{"name":"Ostatní veřejné služby jinde nezařazené.","parents":["Všeobecná veřejná správa a služby","Jiné veřejné služby a činnosti","Ostatní veřejné služby"]},
	"6221":{"name":"Humanitární zahraniční pomoc přímá","parents":["Všeobecná veřejná správa a služby","Jiné veřejné služby a činnosti","Zahraniční pomoc a mezinárodní spolupráce (jinde nezařazená)"]},
	"6222":{"name":"Rozvojová zahraniční pomoc","parents":["Všeobecná veřejná správa a služby","Jiné veřejné služby a činnosti","Zahraniční pomoc a mezinárodní spolupráce (jinde nezařazená)"]},
	"6223":{"name":"Mezinárodní spolupráce (jinde nezařazená)","parents":["Všeobecná veřejná správa a služby","Jiné veřejné služby a činnosti","Zahraniční pomoc a mezinárodní spolupráce (jinde nezařazená)"]},
	"6224":{"name":"Humanitární zahraniční pomoc poskytovaná prostřednictvím mezinárodních organizací","parents":["Všeobecná veřejná správa a služby","Jiné veřejné služby a činnosti","Zahraniční pomoc a mezinárodní spolupráce (jinde nezařazená)"]},
	"6229":{"name":"Ostatní zahraniční pomoc","parents":["Všeobecná veřejná správa a služby","Jiné veřejné služby a činnosti","Zahraniční pomoc a mezinárodní spolupráce (jinde nezařazená)"]},
	"6310":{"name":"Obecné příjmy a výdaje z finančních operací","parents":["Všeobecná veřejná správa a služby","Finanční operace","Obecné příjmy a výdaje z finančních operací"]},
	"6320":{"name":"Pojištění funkčně nespecifikované","parents":["Všeobecná veřejná správa a služby","Finanční operace","Pojištění funkčně nespecifikované"]},
	"6330":{"name":"Převody vlastním fondům v rozpočtech územní úrovně","parents":["Všeobecná veřejná správa a služby","Finanční operace","Převody vlastním fondům v rozpočtech územní úrovně"]},
	"6391":{"name":"Soudní a mimosoudní rehabilitace","parents":["Všeobecná veřejná správa a služby","Finanční operace","Ostatní finanční operace"]},
	"6399":{"name":"Ostatní finanční operace","parents":["Všeobecná veřejná správa a služby","Finanční operace","Ostatní finanční operace"]},
	"6401":{"name":"Transfery všeobecné povahy jiným úrovním vlády","parents":["Všeobecná veřejná správa a služby","Ostatní činnosti","Ostatní činnosti"]},
	"6402":{"name":"Finanční vypořádání minulých let","parents":["Všeobecná veřejná správa a služby","Ostatní činnosti","Ostatní činnosti"]},
	"6409":{"name":"Ostatní činnosti jinde nezařazené","parents":["Všeobecná veřejná správa a služby","Ostatní činnosti","Ostatní činnosti"]}
};