name: Publish Docker Strapi Server
on:
  push:
    paths:
      - 'redesign/server-strapi/**'
      - '.github/workflows/publish-docker-strapi-server.yml'
jobs:
  build-server-strapi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish server-strapi to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: cityvizor/strapi-server
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          workdir: redesign/server-strapi
          snapshot: true
