name: Publish Docker Server Kotlin
on:
  push:
    paths:
      - 'server-kotlin/**'
      - '.github/workflows/publish-docker-server-kotlin.yml'
jobs:
  build-server-kotlin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish server-kotlin to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: cityvizor/server-kotlin
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          workdir: server-kotlin
          snapshot: true

