name: Publish Docker Client Redesign
on:
  push:
    paths:
      - 'landing-page/**'
      - '.github/workflows/publish-docker-landing-page.yml'
jobs:
  build-landing-page:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish landing-page to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: cityvizor/landing-page
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          workdir: landing-page
          buildoptions: "--target prod"
          tags: ${{ github.event_name == 'release' && 'prod' || 'latest' }}